package fracpack

import (
	"fmt"
	"io"
	"strings"
	"unicode"
)

// GenerateViews generates typed view struct source code for the given TypeDefs.
//
// The output is a complete Go source file for the specified package. Each
// TypeDef produces a <Name>View struct with zero-copy accessor methods that
// read fields at compile-time-known byte offsets — no runtime dispatch.
//
// Parameters:
//   - w:          destination writer (typically an os.File)
//   - pkg:        Go package name for the generated file
//   - importPath: import path for the fracpack library (e.g.,
//     "github.com/psibase/psio/fracpack"). When pkg is "fracpack"
//     and importPath is empty, the generator assumes it is producing
//     code inside the fracpack package itself and calls the runtime
//     helpers without a package qualifier.
//   - defs:       TypeDef schemas to generate views for
//
// Usage (in a //go:build ignore file):
//
//	f, _ := os.Create("views_gen.go")
//	defer f.Close()
//	fracpack.GenerateViews(f, "myapp",
//	    "github.com/psibase/psio/fracpack",
//	    []*fracpack.TypeDef{mySchema1, mySchema2})
func GenerateViews(w io.Writer, pkg, importPath string, defs []*TypeDef) error {
	internal := importPath == "" && pkg == "fracpack"
	g := &viewGenerator{
		w:        w,
		defs:     defs,
		nameMap:  make(map[*TypeDef]string),
		internal: internal,
		prefix:   "",
	}
	if !internal {
		g.prefix = "fracpack."
	}
	for _, td := range defs {
		g.nameMap[td] = td.Name
	}
	return g.generate(pkg, importPath)
}

type viewGenerator struct {
	w        io.Writer
	defs     []*TypeDef
	nameMap  map[*TypeDef]string
	internal bool   // generating into the fracpack package itself
	prefix   string // "fracpack." or "" for helper calls
}

func (g *viewGenerator) generate(pkg, importPath string) error {
	g.pf("// Code generated by fracpack viewgen; DO NOT EDIT.\n\n")
	g.pf("package %s\n\n", pkg)

	if !g.internal {
		g.pf("import (\n")
		g.pf("\t\"github.com/psibase/psio/fracpack\"\n")
		g.pf(")\n\n")
	}

	for _, td := range g.defs {
		g.generateType(td)
	}
	return nil
}

func (g *viewGenerator) generateType(td *TypeDef) {
	name := td.Name + "View"
	headerSize := uint32(0)
	if td.Extensible {
		headerSize = 2
	}

	// Compute field offsets.
	offsets := make([]uint32, len(td.Fields))
	var pos uint32
	for i, f := range td.Fields {
		offsets[i] = pos
		pos += f.FixedSize
	}

	// Struct definition.
	g.pf("// %s provides zero-copy typed access to a fracpack-encoded %s.\n", name, td.Name)
	g.pf("type %s struct {\n", name)
	g.pf("\tdata []byte\n")
	g.pf("\tbase uint32\n")
	g.pf("}\n\n")

	// Constructor.
	g.pf("// New%s creates a view over fracpack-encoded %s data.\n", name, td.Name)
	g.pf("// The data must be valid fracpack; call Validate() first.\n")
	g.pf("func New%s(data []byte) %s {\n", name, name)
	g.pf("\treturn %s{data: data, base: 0}\n", name)
	g.pf("}\n\n")

	// Field accessors.
	for i, f := range td.Fields {
		absOff := headerSize + offsets[i]
		methodName := snakeToCamel(f.Name)
		g.generateField(name, methodName, &f, absOff)
	}
}

func (g *viewGenerator) generateField(typeName, methodName string, f *FieldDef, absOff uint32) {
	p := g.prefix // "fracpack." or ""

	switch {
	case f.Kind == KindBool:
		g.pf("func (v %s) %s() bool { return v.data[v.base+%d] != 0 }\n\n",
			typeName, methodName, absOff)

	case f.Kind == KindU8:
		g.pf("func (v %s) %s() uint8 { return v.data[v.base+%d] }\n\n",
			typeName, methodName, absOff)

	case f.Kind == KindI8:
		g.pf("func (v %s) %s() int8 { return %sViewReadI8(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindU16:
		g.pf("func (v %s) %s() uint16 { return %sViewReadU16(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindI16:
		g.pf("func (v %s) %s() int16 { return %sViewReadI16(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindU32:
		g.pf("func (v %s) %s() uint32 { return %sViewReadU32(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindI32:
		g.pf("func (v %s) %s() int32 { return %sViewReadI32(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindU64:
		g.pf("func (v %s) %s() uint64 { return %sViewReadU64(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindI64:
		g.pf("func (v %s) %s() int64 { return %sViewReadI64(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindF32:
		g.pf("func (v %s) %s() float32 { return %sViewReadF32(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindF64:
		g.pf("func (v %s) %s() float64 { return %sViewReadF64(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)

	case f.Kind == KindString:
		g.pf("func (v %s) %sBytes() []byte { return %sViewReadStr(v.data, v.base+%d) }\n\n",
			typeName, methodName, p, absOff)
		g.pf("func (v %s) %s() string { return string(v.%sBytes()) }\n\n",
			typeName, methodName, methodName)

	case f.Kind == KindObject && f.InnerDef != nil:
		innerView := f.InnerDef.Name + "View"
		g.pf("func (v %s) %s() %s {\n", typeName, methodName, innerView)
		g.pf("\tpos := v.base + %d\n", absOff)
		g.pf("\toff := %sViewReadU32(v.data, pos)\n", p)
		g.pf("\treturn %s{data: v.data, base: pos + off}\n", innerView)
		g.pf("}\n\n")

	case f.Kind == KindOptional && f.ElemKind == KindString:
		g.pf("func (v %s) %sPresent() bool {\n", typeName, methodName)
		g.pf("\treturn %sViewReadU32(v.data, v.base+%d) != 1\n", p, absOff)
		g.pf("}\n\n")
		g.pf("func (v %s) %sBytes() ([]byte, bool) {\n", typeName, methodName)
		g.pf("\tpos := v.base + %d\n", absOff)
		g.pf("\toff := %sViewReadU32(v.data, pos)\n", p)
		g.pf("\tif off == 1 { return nil, false }\n")
		g.pf("\tif off == 0 { return nil, true }\n")
		g.pf("\thp := pos + off\n")
		g.pf("\tn := %sViewReadU32(v.data, hp)\n", p)
		g.pf("\treturn v.data[hp+4 : hp+4+n], true\n")
		g.pf("}\n\n")

	case f.Kind == KindOptional && f.ElemKind == KindU32:
		g.pf("func (v %s) %sPresent() bool {\n", typeName, methodName)
		g.pf("\treturn %sViewReadU32(v.data, v.base+%d) != 1\n", p, absOff)
		g.pf("}\n\n")
		g.pf("func (v %s) %s() (uint32, bool) {\n", typeName, methodName)
		g.pf("\tpos := v.base + %d\n", absOff)
		g.pf("\toff := %sViewReadU32(v.data, pos)\n", p)
		g.pf("\tif off == 1 { return 0, false }\n")
		g.pf("\tif off == 0 { return 0, true }\n")
		g.pf("\treturn %sViewReadU32(v.data, pos+off), true\n", p)
		g.pf("}\n\n")

	case f.Kind == KindVec && f.ElemKind == KindString:
		g.pf("func (v %s) %sLen() int {\n", typeName, methodName)
		g.pf("\tpos := v.base + %d\n", absOff)
		g.pf("\toff := %sViewReadU32(v.data, pos)\n", p)
		g.pf("\tif off == 0 { return 0 }\n")
		g.pf("\thp := pos + off\n")
		g.pf("\tbyteCount := %sViewReadU32(v.data, hp)\n", p)
		g.pf("\treturn int(byteCount / 4)\n")
		g.pf("}\n\n")
		g.pf("func (v %s) %sBytesAt(i int) []byte {\n", typeName, methodName)
		g.pf("\tpos := v.base + %d\n", absOff)
		g.pf("\toff := %sViewReadU32(v.data, pos)\n", p)
		g.pf("\thp := pos + off\n")
		g.pf("\telemPos := hp + 4 + uint32(i)*4\n")
		g.pf("\treturn %sViewReadStr(v.data, elemPos)\n", p)
		g.pf("}\n\n")

	case f.Kind == KindVariant && f.InnerDef != nil:
		g.pf("func (v %s) %sTag() uint8 {\n", typeName, methodName)
		g.pf("\tpos := v.base + %d\n", absOff)
		g.pf("\toff := %sViewReadU32(v.data, pos)\n", p)
		g.pf("\treturn v.data[pos+off+4]\n")
		g.pf("}\n\n")

	default:
		g.pf("// %s.%s: unsupported kind %d (skipped)\n\n", typeName, methodName, f.Kind)
	}
}

func (g *viewGenerator) pf(format string, args ...interface{}) {
	fmt.Fprintf(g.w, format, args...)
}

// snakeToCamel converts a snake_case field name to exported CamelCase.
func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		upper := strings.ToUpper(p)
		switch upper {
		case "ID", "URL", "HTTP", "API", "DBM":
			b.WriteString(upper)
		default:
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}
