// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <global_0_wasm>", "[global_0_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "get-a")->to_ui32() == UINT32_C(4294967294));
   CHECK(bkend.call_with_return("env", "get-b")->to_ui64() == UINT64_C(18446744073709551611));
   CHECK(bkend.call_with_return("env", "get-x")->to_ui32() == UINT32_C(4294967284));
   CHECK(bkend.call_with_return("env", "get-y")->to_ui64() == UINT64_C(18446744073709551601));
   CHECK(bkend.call_with_return("env", "get-z1")->to_ui32() == UINT32_C(666));
   CHECK(bkend.call_with_return("env", "get-z2")->to_ui64() == UINT64_C(666));
   CHECK(bkend.call_with_return("env", "get-z3")->to_ui32() == UINT32_C(42));
   CHECK(bkend.call_with_return("env", "get-z4")->to_ui64() == UINT64_C(43));
   CHECK(bkend.call_with_return("env", "get-z5")->to_ui32() == UINT32_C(708));
   CHECK(bkend.call_with_return("env", "get-z6")->to_ui64() == UINT64_C(708));
   CHECK(bit_cast<uint32_t>(bkend.call_with_return("env", "get-3")->to_f32()) == UINT32_C(3225419776));
   CHECK(bit_cast<uint64_t>(bkend.call_with_return("env", "get-4")->to_f64()) == UINT64_C(13839561654909534208));
   CHECK(bit_cast<uint32_t>(bkend.call_with_return("env", "get-7")->to_f32()) == UINT32_C(3243245568));
   CHECK(bit_cast<uint64_t>(bkend.call_with_return("env", "get-8")->to_f64()) == UINT64_C(13847442954257432576));
   CHECK(!bkend.call_with_return("env", "set-x", UINT32_C(6)));
   CHECK(!bkend.call_with_return("env", "set-y", UINT64_C(7)));
   CHECK(!bkend.call_with_return("env", "set-7", bit_cast<float>(UINT32_C(1090519040))));
   CHECK(!bkend.call_with_return("env", "set-8", bit_cast<double>(UINT64_C(4621256167635550208))));
   CHECK(bkend.call_with_return("env", "get-x")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "get-y")->to_ui64() == UINT64_C(7));
   CHECK(bit_cast<uint32_t>(bkend.call_with_return("env", "get-7")->to_f32()) == UINT32_C(1090519040));
   CHECK(bit_cast<uint64_t>(bkend.call_with_return("env", "get-8")->to_f64()) == UINT64_C(4621256167635550208));
   CHECK(!bkend.call_with_return("env", "set-7", bit_cast<float>(UINT32_C(1090519040))));
   CHECK(!bkend.call_with_return("env", "set-8", bit_cast<double>(UINT64_C(4621256167635550208))));
   CHECK(bkend.call_with_return("env", "get-x")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "get-y")->to_ui64() == UINT64_C(7));
   CHECK(bit_cast<uint32_t>(bkend.call_with_return("env", "get-7")->to_f32()) == UINT32_C(1090519040));
   CHECK(bit_cast<uint64_t>(bkend.call_with_return("env", "get-8")->to_f64()) == UINT64_C(4621256167635550208));
   CHECK(bkend.call_with_return("env", "as-select-first")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-select-mid")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-select-last")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-loop-first")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-loop-mid")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-loop-last")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-if-condition")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-if-then")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-if-else")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-br_if-first")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-br_if-last")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-br_table-first")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-br_table-last")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-call_indirect-first")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-call_indirect-mid")->to_ui32() == UINT32_C(2));
   CHECK_THROWS_AS(bkend("env", "as-call_indirect-last"), std::exception);
   CHECK(!bkend.call_with_return("env", "as-store-first"));
   CHECK(!bkend.call_with_return("env", "as-store-last"));
   CHECK(bkend.call_with_return("env", "as-load-operand")->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-memory.grow-value")->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-call-value")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-return-value")->to_ui32() == UINT32_C(6));
   CHECK(!bkend.call_with_return("env", "as-drop-operand"));
   CHECK(bkend.call_with_return("env", "as-br-value")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-local.set-value", UINT32_C(1))->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-local.tee-value", UINT32_C(1))->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-global.set-value")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "as-unary-operand")->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-binary-operand")->to_ui32() == UINT32_C(36));
   CHECK(bkend.call_with_return("env", "as-compare-operand")->to_ui32() == UINT32_C(1));
}

BACKEND_TEST_CASE( "Testing wasm <global_1_wasm>", "[global_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.1.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_10_wasm>", "[global_10_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.10.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_11_wasm>", "[global_11_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.11.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_12_wasm>", "[global_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.12.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_13_wasm>", "[global_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.13.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_14_wasm>", "[global_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.14.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_15_wasm>", "[global_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.15.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_16_wasm>", "[global_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.16.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_17_wasm>", "[global_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.17.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_18_wasm>", "[global_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.18.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_19_wasm>", "[global_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.19.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_2_wasm>", "[global_2_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.2.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_20_wasm>", "[global_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.20.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_21_wasm>", "[global_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.21.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_22_wasm>", "[global_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.22.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_23_wasm>", "[global_23_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.23.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_24_wasm>", "[global_24_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.24.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_25_wasm>", "[global_25_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.25.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_26_wasm>", "[global_26_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.26.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_27_wasm>", "[global_27_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.27.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_28_wasm>", "[global_28_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.28.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_29_wasm>", "[global_29_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.29.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_3_wasm>", "[global_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.3.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_30_wasm>", "[global_30_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.30.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_31_wasm>", "[global_31_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.31.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_32_wasm>", "[global_32_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.32.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_33_wasm>", "[global_33_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.33.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_34_wasm>", "[global_34_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.34.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_35_wasm>", "[global_35_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.35.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_36_wasm>", "[global_36_wasm_tests]" ) {
   register_spectest_imports();
   using backend_t = backend<spectest_rhf, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.36.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_37_wasm>", "[global_37_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.37.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_38_wasm>", "[global_38_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.38.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_39_wasm>", "[global_39_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.39.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_4_wasm>", "[global_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.4.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_40_wasm>", "[global_40_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.40.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_41_wasm>", "[global_41_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.41.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_42_wasm>", "[global_42_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.42.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_43_wasm>", "[global_43_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.43.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_44_wasm>", "[global_44_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.44.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_45_wasm>", "[global_45_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.45.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_46_wasm>", "[global_46_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.46.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_47_wasm>", "[global_47_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.47.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_48_wasm>", "[global_48_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.48.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_49_wasm>", "[global_49_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.49.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <global_5_wasm>", "[global_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.5.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_50_wasm>", "[global_50_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.50.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "get-data", UINT32_C(4))->to_ui32() == UINT32_C(1145324612));
   CHECK(bkend.call_with_return("env", "get-data", UINT32_C(8))->to_ui32() == UINT32_C(2290649224));
}

BACKEND_TEST_CASE( "Testing wasm <global_51_wasm>", "[global_51_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.51.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_52_wasm>", "[global_52_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.52.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_6_wasm>", "[global_6_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.6.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_7_wasm>", "[global_7_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.7.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_8_wasm>", "[global_8_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.8.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <global_9_wasm>", "[global_9_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "global.9.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

