// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <i16x8_relaxed_q15mulr_s_0_wasm>", "[i16x8_relaxed_q15mulr_s_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i16x8_relaxed_q15mulr_s.0.wasm");
   backend_t bkend( code, &wa );

   { auto _r = bkend.call_with_return("env", "i16x8.relaxed_q15mulr_s", make_v128_i16(32768u,32769u,32767u,0u,0u,0u,0u,0u), make_v128_i16(32768u,32768u,32767u,0u,0u,0u,0u,0u))->to_v128();
     CHECK((_r == make_v128_i16(32768u,32767u,32766u,0u,0u,0u,0u,0u) || _r == make_v128_i16(32767u,32767u,32766u,0u,0u,0u,0u,0u))); }
   CHECK(bkend.call_with_return("env", "i16x8.relaxed_q15mulr_s_cmp", make_v128_i16(32768u,32769u,32767u,0u,0u,0u,0u,0u), make_v128_i16(32768u,32768u,32767u,0u,0u,0u,0u,0u))->to_v128() == make_v128_i16(65535u,65535u,65535u,65535u,65535u,65535u,65535u,65535u));
}

