// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <i32x4_relaxed_trunc_0_wasm>", "[i32x4_relaxed_trunc_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i32x4_relaxed_trunc.0.wasm");
   backend_t bkend( code, &wa );

}

