// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <if_0_wasm>", "[if_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(!bkend.call_with_return("env", "empty", UINT32_C(0)));
   CHECK(!bkend.call_with_return("env", "empty", UINT32_C(1)));
   CHECK(!bkend.call_with_return("env", "empty", UINT32_C(100)));
   CHECK(!bkend.call_with_return("env", "empty", UINT32_C(4294967294)));
   CHECK(bkend.call_with_return("env", "singular", UINT32_C(0))->to_ui32() == UINT32_C(8));
   CHECK(bkend.call_with_return("env", "singular", UINT32_C(1))->to_ui32() == UINT32_C(7));
   CHECK(bkend.call_with_return("env", "singular", UINT32_C(10))->to_ui32() == UINT32_C(7));
   CHECK(bkend.call_with_return("env", "singular", UINT32_C(4294967286))->to_ui32() == UINT32_C(7));
   CHECK(bkend.call_with_return("env", "multi", UINT32_C(0))->to_ui32() == UINT32_C(9));
   CHECK(bkend.call_with_return("env", "multi", UINT32_C(1))->to_ui32() == UINT32_C(8));
   CHECK(bkend.call_with_return("env", "multi", UINT32_C(13))->to_ui32() == UINT32_C(8));
   CHECK(bkend.call_with_return("env", "multi", UINT32_C(4294967291))->to_ui32() == UINT32_C(8));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(0), UINT32_C(0))->to_ui32() == UINT32_C(11));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(1), UINT32_C(0))->to_ui32() == UINT32_C(10));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(0), UINT32_C(1))->to_ui32() == UINT32_C(10));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(3), UINT32_C(2))->to_ui32() == UINT32_C(9));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(0), UINT32_C(4294967196))->to_ui32() == UINT32_C(10));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(10), UINT32_C(10))->to_ui32() == UINT32_C(9));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(0), UINT32_C(4294967295))->to_ui32() == UINT32_C(10));
   CHECK(bkend.call_with_return("env", "nested", UINT32_C(4294967185), UINT32_C(4294967294))->to_ui32() == UINT32_C(9));
   CHECK(bkend.call_with_return("env", "as-select-first", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-select-first", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-select-mid", UINT32_C(0))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-select-mid", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-select-last", UINT32_C(0))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "as-select-last", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-loop-first", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-loop-first", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-loop-mid", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-loop-mid", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-loop-last", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-loop-last", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-if-condition", UINT32_C(0))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "as-if-condition", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-br_if-first", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-br_if-first", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-br_if-last", UINT32_C(0))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "as-br_if-last", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-br_table-first", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-br_table-first", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-br_table-last", UINT32_C(0))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-br_table-last", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-call_indirect-first", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-call_indirect-first", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-call_indirect-mid", UINT32_C(0))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-call_indirect-mid", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "as-call_indirect-last", UINT32_C(0))->to_ui32() == UINT32_C(2));
   CHECK_THROWS_AS(bkend("env", "as-call_indirect-last", UINT32_C(1)), std::exception);
   CHECK(!bkend.call_with_return("env", "as-store-first", UINT32_C(0)));
   CHECK(!bkend.call_with_return("env", "as-store-first", UINT32_C(1)));
   CHECK(!bkend.call_with_return("env", "as-store-last", UINT32_C(0)));
   CHECK(!bkend.call_with_return("env", "as-store-last", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "as-memory.grow-value", UINT32_C(0))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-memory.grow-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-call-value", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-call-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-return-value", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-return-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(!bkend.call_with_return("env", "as-drop-operand", UINT32_C(0)));
   CHECK(!bkend.call_with_return("env", "as-drop-operand", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "as-br-value", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-br-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-local.set-value", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-local.set-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-local.tee-value", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-local.tee-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-global.set-value", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-global.set-value", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-load-operand", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-load-operand", UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-unary-operand", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-unary-operand", UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-unary-operand", UINT32_C(4294967295))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-binary-operand", UINT32_C(0), UINT32_C(0))->to_ui32() == UINT32_C(15));
   CHECK(bkend.call_with_return("env", "as-binary-operand", UINT32_C(0), UINT32_C(1))->to_ui32() == UINT32_C(4294967284));
   CHECK(bkend.call_with_return("env", "as-binary-operand", UINT32_C(1), UINT32_C(0))->to_ui32() == UINT32_C(4294967281));
   CHECK(bkend.call_with_return("env", "as-binary-operand", UINT32_C(1), UINT32_C(1))->to_ui32() == UINT32_C(12));
   CHECK(bkend.call_with_return("env", "as-test-operand", UINT32_C(0))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-test-operand", UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-compare-operand", UINT32_C(0), UINT32_C(0))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-compare-operand", UINT32_C(0), UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-compare-operand", UINT32_C(1), UINT32_C(0))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-compare-operand", UINT32_C(1), UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-binary-operands", UINT32_C(0))->to_ui32() == UINT32_C(4294967284));
   CHECK(bkend.call_with_return("env", "as-binary-operands", UINT32_C(1))->to_ui32() == UINT32_C(12));
   CHECK(bkend.call_with_return("env", "as-compare-operands", UINT32_C(0))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "as-compare-operands", UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "as-mixed-operands", UINT32_C(0))->to_ui32() == UINT32_C(4294967293));
   CHECK(bkend.call_with_return("env", "as-mixed-operands", UINT32_C(1))->to_ui32() == UINT32_C(27));
   CHECK(bkend.call_with_return("env", "break-bare")->to_ui32() == UINT32_C(19));
   CHECK(bkend.call_with_return("env", "break-value", UINT32_C(1))->to_ui32() == UINT32_C(18));
   CHECK(bkend.call_with_return("env", "break-value", UINT32_C(0))->to_ui32() == UINT32_C(21));
   CHECK(bkend.call_with_return("env", "break-multi-value", UINT32_C(0))->to_ui32() == UINT32_C(4294967278));
   CHECK(bkend.call_with_return("env", "break-multi-value", UINT32_C(1))->to_ui32() == UINT32_C(18));
   CHECK(bkend.call_with_return("env", "param", UINT32_C(0))->to_ui32() == UINT32_C(4294967295));
   CHECK(bkend.call_with_return("env", "param", UINT32_C(1))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "params", UINT32_C(0))->to_ui32() == UINT32_C(4294967295));
   CHECK(bkend.call_with_return("env", "params", UINT32_C(1))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "params-id", UINT32_C(0))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "params-id", UINT32_C(1))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "param-break", UINT32_C(0))->to_ui32() == UINT32_C(4294967295));
   CHECK(bkend.call_with_return("env", "param-break", UINT32_C(1))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "params-break", UINT32_C(0))->to_ui32() == UINT32_C(4294967295));
   CHECK(bkend.call_with_return("env", "params-break", UINT32_C(1))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "params-id-break", UINT32_C(0))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "params-id-break", UINT32_C(1))->to_ui32() == UINT32_C(3));
   CHECK(bkend.call_with_return("env", "effects", UINT32_C(1))->to_ui32() == UINT32_C(4294967282));
   CHECK(bkend.call_with_return("env", "effects", UINT32_C(0))->to_ui32() == UINT32_C(4294967290));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(0), UINT64_C(0), UINT32_C(0))->to_ui64() == UINT64_C(0));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(100), UINT64_C(124), UINT32_C(0))->to_ui64() == UINT64_C(224));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(18446744073709551615), UINT64_C(0), UINT32_C(0))->to_ui64() == UINT64_C(18446744073709551615));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(18446744073709551615), UINT64_C(1), UINT32_C(0))->to_ui64() == UINT64_C(0));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615), UINT32_C(0))->to_ui64() == UINT64_C(18446744073709551614));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(18446744073709551615), UINT64_C(0), UINT32_C(1))->to_ui64() == UINT64_C(0));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(18446744073709551615), UINT64_C(1), UINT32_C(1))->to_ui64() == UINT64_C(1));
   CHECK(bkend.call_with_return("env", "add64_u_with_carry", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808), UINT32_C(0))->to_ui64() == UINT64_C(0));
   CHECK(bkend.call_with_return("env", "add64_u_saturated", UINT64_C(0), UINT64_C(0))->to_ui64() == UINT64_C(0));
   CHECK(bkend.call_with_return("env", "add64_u_saturated", UINT64_C(1230), UINT64_C(23))->to_ui64() == UINT64_C(1253));
   CHECK(bkend.call_with_return("env", "add64_u_saturated", UINT64_C(18446744073709551615), UINT64_C(0))->to_ui64() == UINT64_C(18446744073709551615));
   CHECK(bkend.call_with_return("env", "add64_u_saturated", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT64_C(18446744073709551615));
   CHECK(bkend.call_with_return("env", "add64_u_saturated", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT64_C(18446744073709551615));
   CHECK(bkend.call_with_return("env", "add64_u_saturated", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui64() == UINT64_C(18446744073709551615));
   CHECK(!bkend.call_with_return("env", "type-use"));
   CHECK(!bkend.call_with_return("env", "atypical-condition"));
}

BACKEND_TEST_CASE( "Testing wasm <if_100_wasm>", "[if_100_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.100.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_101_wasm>", "[if_101_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.101.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_102_wasm>", "[if_102_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.102.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_103_wasm>", "[if_103_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.103.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_12_wasm>", "[if_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.12.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_13_wasm>", "[if_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.13.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_14_wasm>", "[if_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.14.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_15_wasm>", "[if_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.15.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_16_wasm>", "[if_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.16.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_17_wasm>", "[if_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.17.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_18_wasm>", "[if_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.18.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_19_wasm>", "[if_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.19.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_20_wasm>", "[if_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.20.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_21_wasm>", "[if_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.21.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_22_wasm>", "[if_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.22.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_23_wasm>", "[if_23_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.23.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_24_wasm>", "[if_24_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.24.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_25_wasm>", "[if_25_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.25.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_26_wasm>", "[if_26_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.26.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_27_wasm>", "[if_27_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.27.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_28_wasm>", "[if_28_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.28.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_29_wasm>", "[if_29_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.29.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_30_wasm>", "[if_30_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.30.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_31_wasm>", "[if_31_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.31.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_32_wasm>", "[if_32_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.32.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_33_wasm>", "[if_33_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.33.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_34_wasm>", "[if_34_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.34.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_35_wasm>", "[if_35_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.35.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_36_wasm>", "[if_36_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.36.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_37_wasm>", "[if_37_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.37.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_38_wasm>", "[if_38_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.38.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_39_wasm>", "[if_39_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.39.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_40_wasm>", "[if_40_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.40.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_41_wasm>", "[if_41_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.41.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_42_wasm>", "[if_42_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.42.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_43_wasm>", "[if_43_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.43.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_44_wasm>", "[if_44_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.44.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_45_wasm>", "[if_45_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.45.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_46_wasm>", "[if_46_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.46.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_47_wasm>", "[if_47_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.47.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_48_wasm>", "[if_48_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.48.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_49_wasm>", "[if_49_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.49.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_50_wasm>", "[if_50_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.50.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_51_wasm>", "[if_51_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.51.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_52_wasm>", "[if_52_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.52.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_53_wasm>", "[if_53_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.53.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_54_wasm>", "[if_54_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.54.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_55_wasm>", "[if_55_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.55.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_56_wasm>", "[if_56_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.56.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_57_wasm>", "[if_57_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.57.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_58_wasm>", "[if_58_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.58.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_59_wasm>", "[if_59_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.59.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_60_wasm>", "[if_60_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.60.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_61_wasm>", "[if_61_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.61.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_62_wasm>", "[if_62_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.62.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_63_wasm>", "[if_63_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.63.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_64_wasm>", "[if_64_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.64.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_65_wasm>", "[if_65_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.65.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_66_wasm>", "[if_66_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.66.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_67_wasm>", "[if_67_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.67.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_68_wasm>", "[if_68_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.68.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_69_wasm>", "[if_69_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.69.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_70_wasm>", "[if_70_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.70.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_71_wasm>", "[if_71_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.71.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_72_wasm>", "[if_72_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.72.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_73_wasm>", "[if_73_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.73.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_74_wasm>", "[if_74_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.74.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_75_wasm>", "[if_75_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.75.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_76_wasm>", "[if_76_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.76.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_77_wasm>", "[if_77_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.77.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_78_wasm>", "[if_78_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.78.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_79_wasm>", "[if_79_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.79.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_80_wasm>", "[if_80_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.80.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_81_wasm>", "[if_81_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.81.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_82_wasm>", "[if_82_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.82.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_83_wasm>", "[if_83_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.83.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_84_wasm>", "[if_84_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.84.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_85_wasm>", "[if_85_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.85.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_86_wasm>", "[if_86_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.86.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_87_wasm>", "[if_87_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.87.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_88_wasm>", "[if_88_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.88.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_89_wasm>", "[if_89_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.89.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_90_wasm>", "[if_90_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.90.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_91_wasm>", "[if_91_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.91.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_92_wasm>", "[if_92_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.92.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_93_wasm>", "[if_93_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.93.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_94_wasm>", "[if_94_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.94.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_95_wasm>", "[if_95_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.95.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_96_wasm>", "[if_96_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.96.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_97_wasm>", "[if_97_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.97.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_98_wasm>", "[if_98_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.98.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <if_99_wasm>", "[if_99_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "if.99.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

