// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <memory_grow_0_wasm>", "[memory_grow_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_grow.0.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <memory_grow_2_wasm>", "[memory_grow_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_grow.2.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "size1")->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "size2")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "grow1", UINT32_C(3))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "grow1", UINT32_C(4))->to_ui32() == UINT32_C(4));
   CHECK(bkend.call_with_return("env", "grow1", UINT32_C(1))->to_ui32() == UINT32_C(8));
   CHECK(bkend.call_with_return("env", "grow2", UINT32_C(1))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "grow2", UINT32_C(1))->to_ui32() == UINT32_C(3));
}

