// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <relaxed_min_max_0_wasm>", "[relaxed_min_max_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "relaxed_min_max.0.wasm");
   backend_t bkend( code, &wa );

   { auto _r = bkend.call_with_return("env", "f32x4.relaxed_min", make_v128_f32(4290772992u,2143289344u,0u,0u), make_v128_f32(0u,0u,4290772992u,2143289344u))->to_v128();
     CHECK((_r == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}} || _r == v128_matcher{nan_canonical_t{},nan_canonical_t{},0u,0u} || _r == v128_matcher{0u,0u,nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f32(0u,0u,0u,0u))); }
   { auto _r = bkend.call_with_return("env", "f32x4.relaxed_min", make_v128_f32(0u,2147483648u,0u,2147483648u), make_v128_f32(2147483648u,0u,0u,2147483648u))->to_v128();
     CHECK((_r == make_v128_f32(2147483648u,2147483648u,0u,2147483648u) || _r == make_v128_f32(0u,2147483648u,0u,2147483648u) || _r == make_v128_f32(2147483648u,0u,0u,2147483648u) || _r == make_v128_f32(2147483648u,2147483648u,0u,2147483648u))); }
   { auto _r = bkend.call_with_return("env", "f32x4.relaxed_max", make_v128_f32(4290772992u,2143289344u,0u,0u), make_v128_f32(0u,0u,4290772992u,2143289344u))->to_v128();
     CHECK((_r == v128_matcher{nan_canonical_t{},nan_canonical_t{},nan_canonical_t{},nan_canonical_t{}} || _r == v128_matcher{nan_canonical_t{},nan_canonical_t{},0u,0u} || _r == v128_matcher{0u,0u,nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f32(0u,0u,0u,0u))); }
   { auto _r = bkend.call_with_return("env", "f32x4.relaxed_max", make_v128_f32(0u,2147483648u,0u,2147483648u), make_v128_f32(2147483648u,0u,0u,2147483648u))->to_v128();
     CHECK((_r == make_v128_f32(0u,0u,0u,2147483648u) || _r == make_v128_f32(0u,2147483648u,0u,2147483648u) || _r == make_v128_f32(2147483648u,0u,0u,2147483648u) || _r == make_v128_f32(2147483648u,2147483648u,0u,2147483648u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_min", make_v128_f64(18444492273895866368u,9221120237041090560u), make_v128_f64(0u,0u))->to_v128();
     CHECK((_r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f64(0u,0u) || _r == make_v128_f64(0u,0u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_min", make_v128_f64(0u,0u), make_v128_f64(18444492273895866368u,9221120237041090560u))->to_v128();
     CHECK((_r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f64(0u,0u) || _r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f64(0u,0u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_min", make_v128_f64(0u,9223372036854775808u), make_v128_f64(9223372036854775808u,0u))->to_v128();
     CHECK((_r == make_v128_f64(9223372036854775808u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(9223372036854775808u,0u) || _r == make_v128_f64(9223372036854775808u,9223372036854775808u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_min", make_v128_f64(0u,9223372036854775808u), make_v128_f64(0u,9223372036854775808u))->to_v128();
     CHECK((_r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_max", make_v128_f64(18444492273895866368u,9221120237041090560u), make_v128_f64(0u,0u))->to_v128();
     CHECK((_r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f64(0u,0u) || _r == make_v128_f64(0u,0u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_max", make_v128_f64(0u,0u), make_v128_f64(18444492273895866368u,9221120237041090560u))->to_v128();
     CHECK((_r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f64(0u,0u) || _r == v128_matcher{nan_canonical_t{},nan_canonical_t{}} || _r == make_v128_f64(0u,0u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_max", make_v128_f64(0u,9223372036854775808u), make_v128_f64(9223372036854775808u,0u))->to_v128();
     CHECK((_r == make_v128_f64(0u,0u) || _r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(9223372036854775808u,0u) || _r == make_v128_f64(9223372036854775808u,9223372036854775808u))); }
   { auto _r = bkend.call_with_return("env", "f64x2.relaxed_max", make_v128_f64(0u,9223372036854775808u), make_v128_f64(0u,9223372036854775808u))->to_v128();
     CHECK((_r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u) || _r == make_v128_f64(0u,9223372036854775808u))); }
   CHECK(bkend.call_with_return("env", "f32x4.relaxed_min_cmp", make_v128_f32(4290772992u,2143289344u,0u,0u), make_v128_f32(0u,0u,4290772992u,2143289344u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
   CHECK(bkend.call_with_return("env", "f32x4.relaxed_min_cmp", make_v128_f32(0u,2147483648u,0u,2147483648u), make_v128_f32(2147483648u,0u,0u,2147483648u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
   CHECK(bkend.call_with_return("env", "f32x4.relaxed_max_cmp", make_v128_f32(4290772992u,2143289344u,0u,0u), make_v128_f32(0u,0u,4290772992u,2143289344u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
   CHECK(bkend.call_with_return("env", "f32x4.relaxed_max_cmp", make_v128_f32(0u,2147483648u,0u,2147483648u), make_v128_f32(2147483648u,0u,0u,2147483648u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_min_cmp", make_v128_f64(18444492273895866368u,9221120237041090560u), make_v128_f64(0u,0u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_min_cmp", make_v128_f64(0u,0u), make_v128_f64(18444492273895866368u,9221120237041090560u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_min_cmp", make_v128_f64(0u,9223372036854775808u), make_v128_f64(9223372036854775808u,0u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_min_cmp", make_v128_f64(0u,9223372036854775808u), make_v128_f64(0u,9223372036854775808u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_max_cmp", make_v128_f64(18444492273895866368u,9221120237041090560u), make_v128_f64(0u,0u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_max_cmp", make_v128_f64(0u,0u), make_v128_f64(18444492273895866368u,9221120237041090560u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_max_cmp", make_v128_f64(0u,9223372036854775808u), make_v128_f64(9223372036854775808u,0u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "f64x2.relaxed_max_cmp", make_v128_f64(0u,9223372036854775808u), make_v128_f64(0u,9223372036854775808u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
}

