// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <relaxed_laneselect_0_wasm>", "[relaxed_laneselect_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "relaxed_laneselect.0.wasm");
   backend_t bkend( code, &wa );

   { auto _r = bkend.call_with_return("env", "i8x16.relaxed_laneselect", make_v128_i8(0u,1u,18u,18u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u), make_v128_i8(16u,17u,52u,52u,20u,21u,22u,23u,24u,25u,26u,27u,28u,29u,30u,31u), make_v128_i8(255u,0u,240u,15u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u))->to_v128();
     CHECK((_r == make_v128_i8(0u,17u,20u,50u,20u,21u,22u,23u,24u,25u,26u,27u,28u,29u,30u,31u) || _r == make_v128_i8(0u,17u,18u,52u,20u,21u,22u,23u,24u,25u,26u,27u,28u,29u,30u,31u))); }
   { auto _r = bkend.call_with_return("env", "i16x8.relaxed_laneselect", make_v128_i16(0u,1u,4660u,4660u,4u,5u,6u,7u), make_v128_i16(8u,9u,22136u,22136u,12u,13u,14u,15u), make_v128_i16(65535u,0u,65280u,255u,0u,0u,0u,0u))->to_v128();
     CHECK((_r == make_v128_i16(0u,9u,4728u,22068u,12u,13u,14u,15u) || _r == make_v128_i16(0u,9u,4660u,22136u,12u,13u,14u,15u))); }
   { auto _r = bkend.call_with_return("env", "i16x8.relaxed_laneselect", make_v128_i16(0u,1u,4660u,4660u,4u,5u,6u,7u), make_v128_i16(8u,9u,22136u,22136u,12u,13u,14u,15u), make_v128_i16(65535u,0u,65280u,128u,0u,0u,0u,0u))->to_v128();
     CHECK((_r == make_v128_i16(0u,9u,4728u,22136u,12u,13u,14u,15u) || _r == make_v128_i16(0u,9u,4660u,22136u,12u,13u,14u,15u) || _r == make_v128_i16(0u,9u,4728u,22068u,12u,13u,14u,15u))); }
   { auto _r = bkend.call_with_return("env", "i32x4.relaxed_laneselect", make_v128_i32(0u,1u,305402420u,305402420u), make_v128_i32(4u,5u,1450727032u,1450727032u), make_v128_i32(4294967295u,0u,4294901760u,65535u))->to_v128();
     CHECK((_r == make_v128_i32(0u,5u,305419896u,1450709556u) || _r == make_v128_i32(0u,5u,305402420u,1450727032u))); }
   { auto _r = bkend.call_with_return("env", "i64x2.relaxed_laneselect", make_v128_i64(0u,1u), make_v128_i64(2u,3u), make_v128_i64(18446744073709551615u,0u))->to_v128();
     CHECK((_r == make_v128_i64(0u,3u) || _r == make_v128_i64(0u,3u))); }
   { auto _r = bkend.call_with_return("env", "i64x2.relaxed_laneselect", make_v128_i64(1311693406324658740u,1311693406324658740u), make_v128_i64(6230825159313872504u,6230825159313872504u), make_v128_i64(18446744069414584320u,4294967295u))->to_v128();
     CHECK((_r == make_v128_i64(1311693407469983352u,6230825158168547892u) || _r == make_v128_i64(1311693406324658740u,6230825159313872504u))); }
   CHECK(bkend.call_with_return("env", "i8x16.relaxed_laneselect_cmp", make_v128_i8(0u,1u,18u,18u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u), make_v128_i8(16u,17u,52u,52u,20u,21u,22u,23u,24u,25u,26u,27u,28u,29u,30u,31u), make_v128_i8(255u,0u,240u,15u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u))->to_v128() == make_v128_i8(255u,255u,255u,255u,255u,255u,255u,255u,255u,255u,255u,255u,255u,255u,255u,255u));
   CHECK(bkend.call_with_return("env", "i16x8.relaxed_laneselect_cmp", make_v128_i16(0u,1u,4660u,4660u,4u,5u,6u,7u), make_v128_i16(8u,9u,22136u,22136u,12u,13u,14u,15u), make_v128_i16(65535u,0u,65280u,255u,0u,0u,0u,0u))->to_v128() == make_v128_i16(65535u,65535u,65535u,65535u,65535u,65535u,65535u,65535u));
   CHECK(bkend.call_with_return("env", "i32x4.relaxed_laneselect_cmp", make_v128_i32(0u,1u,305402420u,305402420u), make_v128_i32(4u,5u,1450727032u,1450727032u), make_v128_i32(4294967295u,0u,4294901760u,65535u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
   CHECK(bkend.call_with_return("env", "i64x2.relaxed_laneselect_cmp", make_v128_i64(0u,1u), make_v128_i64(2u,3u), make_v128_i64(18446744073709551615u,0u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
   CHECK(bkend.call_with_return("env", "i64x2.relaxed_laneselect_cmp", make_v128_i64(1311693406324658740u,1311693406324658740u), make_v128_i64(6230825159313872504u,6230825159313872504u), make_v128_i64(18446744069414584320u,4294967295u))->to_v128() == make_v128_i64(18446744073709551615u,18446744073709551615u));
}

