// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <relaxed_dot_product_0_wasm>", "[relaxed_dot_product_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "relaxed_dot_product.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "i16x8.relaxed_dot_i8x16_i7x16_s", make_v128_i8(0u,1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u), make_v128_i8(0u,1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u))->to_v128() == make_v128_i16(1u,13u,41u,85u,145u,221u,313u,421u));
   CHECK(bkend.call_with_return("env", "i16x8.relaxed_dot_i8x16_i7x16_s", make_v128_i8(128u,128u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(127u,127u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u))->to_v128() == make_v128_i16(33024u,32258u,0u,0u,0u,0u,0u,0u));
   { auto _r = bkend.call_with_return("env", "i16x8.relaxed_dot_i8x16_i7x16_s", make_v128_i8(128u,128u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(129u,129u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u))->to_v128();
     CHECK((_r == make_v128_i16(32768u,0u,0u,0u,0u,0u,0u,0u) || _r == make_v128_i16(32512u,0u,0u,0u,0u,0u,0u,0u) || _r == make_v128_i16(33024u,0u,0u,0u,0u,0u,0u,0u))); }
   CHECK(bkend.call_with_return("env", "i32x4.relaxed_dot_i8x16_i7x16_add_s", make_v128_i8(0u,1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u), make_v128_i8(0u,1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u), make_v128_i32(0u,1u,2u,3u))->to_v128() == make_v128_i32(14u,127u,368u,737u));
   CHECK(bkend.call_with_return("env", "i32x4.relaxed_dot_i8x16_i7x16_add_s", make_v128_i8(128u,128u,128u,128u,127u,127u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(127u,127u,127u,127u,127u,127u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i32(1u,2u,3u,4u))->to_v128() == make_v128_i32(4294902273u,64518u,3u,4u));
   { auto _r = bkend.call_with_return("env", "i32x4.relaxed_dot_i8x16_i7x16_add_s", make_v128_i8(128u,128u,128u,128u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(129u,129u,129u,129u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i32(1u,2u,3u,4u))->to_v128();
     CHECK((_r == make_v128_i32(4294901249u,2u,3u,4u) || _r == make_v128_i32(4294901761u,2u,3u,4u) || _r == make_v128_i32(65025u,2u,3u,4u) || _r == make_v128_i32(66049u,2u,3u,4u))); }
   CHECK(bkend.call_with_return("env", "i16x8.relaxed_dot_i8x16_i7x16_s_cmp", make_v128_i8(128u,128u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(127u,127u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u))->to_v128() == make_v128_i16(65535u,65535u,65535u,65535u,65535u,65535u,65535u,65535u));
   CHECK(bkend.call_with_return("env", "i32x4.relaxed_dot_i8x16_i7x16_add_s_cmp", make_v128_i8(128u,128u,128u,128u,127u,127u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(127u,127u,127u,127u,127u,127u,127u,127u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i32(1u,2u,3u,4u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
   CHECK(bkend.call_with_return("env", "i16x8.relaxed_dot_i8x16_i7x16_s_cmp", make_v128_i8(128u,128u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(129u,129u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u))->to_v128() == make_v128_i16(65535u,65535u,65535u,65535u,65535u,65535u,65535u,65535u));
   CHECK(bkend.call_with_return("env", "i32x4.relaxed_dot_i8x16_i7x16_add_s_cmp", make_v128_i8(128u,128u,128u,128u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i8(129u,129u,129u,129u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), make_v128_i32(1u,2u,3u,4u))->to_v128() == make_v128_i32(4294967295u,4294967295u,4294967295u,4294967295u));
}

