// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <simd_select_0_wasm>", "[simd_select_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "simd_select.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "select_v128_i32", make_v128_i32(1u,2u,3u,4u), make_v128_i32(5u,6u,7u,8u), UINT32_C(1))->to_v128() == make_v128_i32(1u,2u,3u,4u));
   CHECK(bkend.call_with_return("env", "select_v128_i32", make_v128_i32(1u,2u,3u,4u), make_v128_i32(5u,6u,7u,8u), UINT32_C(0))->to_v128() == make_v128_i32(5u,6u,7u,8u));
   CHECK(bkend.call_with_return("env", "select_v128_i32", make_v128_f32(1065353216u,1073741824u,1077936128u,1082130432u), make_v128_f32(1084227584u,1086324736u,1088421888u,1090519040u), UINT32_C(4294967295))->to_v128() == make_v128_f32(1065353216u,1073741824u,1077936128u,1082130432u));
   CHECK(bkend.call_with_return("env", "select_v128_i32", make_v128_f32(3217031168u,3223322624u,3227516928u,3230662656u), make_v128_f32(1092091904u,1091043328u,1089470464u,1087373312u), UINT32_C(0))->to_v128() == make_v128_f32(1092091904u,1091043328u,1089470464u,1087373312u));
   CHECK(bkend.call_with_return("env", "select_v128_i32", make_v128_i8(1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u,16u), make_v128_i8(16u,15u,14u,13u,12u,11u,10u,9u,8u,7u,6u,5u,4u,3u,2u,1u), UINT32_C(123))->to_v128() == make_v128_i8(1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,14u,15u,16u));
   CHECK(bkend.call_with_return("env", "select_v128_i32", make_v128_i8(1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u), make_v128_i8(0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u), UINT32_C(0))->to_v128() == make_v128_i8(0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u));
}

