// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam::detail;
using namespace psizam;
using namespace psizam::detail;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <table_grow_1_wasm>", "[table_grow_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.1.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "grow")->to_ui32() == UINT32_C(4294967295));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_10_wasm>", "[table_grow_10_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.10.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_11_wasm>", "[table_grow_11_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.11.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_12_wasm>", "[table_grow_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.12.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_13_wasm>", "[table_grow_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.13.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_14_wasm>", "[table_grow_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.14.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_2_wasm>", "[table_grow_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.2.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "grow", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(0))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(2))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(800))->to_ui32() == UINT32_C(3));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_3_wasm>", "[table_grow_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.3.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "grow", UINT32_C(0))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(1))->to_ui32() == UINT32_C(0));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(1))->to_ui32() == UINT32_C(1));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(2))->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(6))->to_ui32() == UINT32_C(4));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(0))->to_ui32() == UINT32_C(10));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(1))->to_ui32() == UINT32_C(4294967295));
   CHECK(bkend.call_with_return("env", "grow", UINT32_C(65536))->to_ui32() == UINT32_C(4294967295));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_4_wasm>", "[table_grow_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.4.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "grow", UINT32_C(10))->to_ui32() == UINT32_C(10));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_5_wasm>", "[table_grow_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.5.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "grow")->to_ui32() == UINT32_C(1));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_6_wasm>", "[table_grow_6_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.6.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "grow")->to_ui32() == UINT32_C(2));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_7_wasm>", "[table_grow_7_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.7.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(3));
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_8_wasm>", "[table_grow_8_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.8.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_grow_9_wasm>", "[table_grow_9_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_grow.9.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

