// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <catch2/catch.hpp>
#include <utils.hpp>
#include <wasm_config.hpp>
#include <psizam/backend.hpp>

using namespace psizam;
using namespace psizam;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <table_size_0_wasm>", "[table_size_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_size.0.wasm");
   backend_t bkend( code, &wa );

   CHECK(bkend.call_with_return("env", "size-t0")->to_ui32() == UINT32_C(0));
   CHECK(!bkend.call_with_return("env", "grow-t0", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "size-t0")->to_ui32() == UINT32_C(1));
   CHECK(!bkend.call_with_return("env", "grow-t0", UINT32_C(4)));
   CHECK(bkend.call_with_return("env", "size-t0")->to_ui32() == UINT32_C(5));
   CHECK(!bkend.call_with_return("env", "grow-t0", UINT32_C(0)));
   CHECK(bkend.call_with_return("env", "size-t0")->to_ui32() == UINT32_C(5));
   CHECK(bkend.call_with_return("env", "size-t1")->to_ui32() == UINT32_C(1));
   CHECK(!bkend.call_with_return("env", "grow-t1", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "size-t1")->to_ui32() == UINT32_C(2));
   CHECK(!bkend.call_with_return("env", "grow-t1", UINT32_C(4)));
   CHECK(bkend.call_with_return("env", "size-t1")->to_ui32() == UINT32_C(6));
   CHECK(!bkend.call_with_return("env", "grow-t1", UINT32_C(0)));
   CHECK(bkend.call_with_return("env", "size-t1")->to_ui32() == UINT32_C(6));
   CHECK(bkend.call_with_return("env", "size-t2")->to_ui32() == UINT32_C(0));
   CHECK(!bkend.call_with_return("env", "grow-t2", UINT32_C(3)));
   CHECK(bkend.call_with_return("env", "size-t2")->to_ui32() == UINT32_C(0));
   CHECK(!bkend.call_with_return("env", "grow-t2", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "size-t2")->to_ui32() == UINT32_C(1));
   CHECK(!bkend.call_with_return("env", "grow-t2", UINT32_C(0)));
   CHECK(bkend.call_with_return("env", "size-t2")->to_ui32() == UINT32_C(1));
   CHECK(!bkend.call_with_return("env", "grow-t2", UINT32_C(4)));
   CHECK(bkend.call_with_return("env", "size-t2")->to_ui32() == UINT32_C(1));
   CHECK(!bkend.call_with_return("env", "grow-t2", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "size-t2")->to_ui32() == UINT32_C(2));
   CHECK(bkend.call_with_return("env", "size-t3")->to_ui32() == UINT32_C(3));
   CHECK(!bkend.call_with_return("env", "grow-t3", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "size-t3")->to_ui32() == UINT32_C(4));
   CHECK(!bkend.call_with_return("env", "grow-t3", UINT32_C(3)));
   CHECK(bkend.call_with_return("env", "size-t3")->to_ui32() == UINT32_C(7));
   CHECK(!bkend.call_with_return("env", "grow-t3", UINT32_C(0)));
   CHECK(bkend.call_with_return("env", "size-t3")->to_ui32() == UINT32_C(7));
   CHECK(!bkend.call_with_return("env", "grow-t3", UINT32_C(2)));
   CHECK(bkend.call_with_return("env", "size-t3")->to_ui32() == UINT32_C(7));
   CHECK(!bkend.call_with_return("env", "grow-t3", UINT32_C(1)));
   CHECK(bkend.call_with_return("env", "size-t3")->to_ui32() == UINT32_C(8));
}

BACKEND_TEST_CASE( "Testing wasm <table_size_1_wasm>", "[table_size_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_size.1.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <table_size_2_wasm>", "[table_size_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "table_size.2.wasm");
   CHECK_THROWS_AS(backend_t(code, nullptr), std::exception);
}

