// Code generated by fracpack viewgen; DO NOT EDIT.

package fracpack

// PointView provides zero-copy typed access to a fracpack-encoded Point.
type PointView struct {
	data []byte
	base uint32
}

// NewPointView creates a view over fracpack-encoded Point data.
// The data must be valid fracpack; call Validate() first.
func NewPointView(data []byte) PointView {
	return PointView{data: data, base: 0}
}

func (v PointView) X() float64 { return ViewReadF64(v.data, v.base+0) }

func (v PointView) Y() float64 { return ViewReadF64(v.data, v.base+8) }

// UserProfileView provides zero-copy typed access to a fracpack-encoded UserProfile.
type UserProfileView struct {
	data []byte
	base uint32
}

// NewUserProfileView creates a view over fracpack-encoded UserProfile data.
// The data must be valid fracpack; call Validate() first.
func NewUserProfileView(data []byte) UserProfileView {
	return UserProfileView{data: data, base: 0}
}

func (v UserProfileView) ID() uint64 { return ViewReadU64(v.data, v.base+2) }

func (v UserProfileView) NameBytes() []byte { return ViewReadStr(v.data, v.base+10) }

func (v UserProfileView) Name() string { return string(v.NameBytes()) }

func (v UserProfileView) EmailBytes() []byte { return ViewReadStr(v.data, v.base+14) }

func (v UserProfileView) Email() string { return string(v.EmailBytes()) }

func (v UserProfileView) BioPresent() bool {
	return ViewReadU32(v.data, v.base+18) != 1
}

func (v UserProfileView) BioBytes() ([]byte, bool) {
	pos := v.base + 18
	off := ViewReadU32(v.data, pos)
	if off == 1 { return nil, false }
	if off == 0 { return nil, true }
	hp := pos + off
	n := ViewReadU32(v.data, hp)
	return v.data[hp+4 : hp+4+n], true
}

func (v UserProfileView) Age() uint32 { return ViewReadU32(v.data, v.base+22) }

func (v UserProfileView) Score() float64 { return ViewReadF64(v.data, v.base+26) }

func (v UserProfileView) TagsLen() int {
	pos := v.base + 34
	off := ViewReadU32(v.data, pos)
	if off == 0 { return 0 }
	hp := pos + off
	byteCount := ViewReadU32(v.data, hp)
	return int(byteCount / 4)
}

func (v UserProfileView) TagsBytesAt(i int) []byte {
	pos := v.base + 34
	off := ViewReadU32(v.data, pos)
	hp := pos + off
	elemPos := hp + 4 + uint32(i)*4
	return ViewReadStr(v.data, elemPos)
}

func (v UserProfileView) Verified() bool { return v.data[v.base+38] != 0 }

// LineItemView provides zero-copy typed access to a fracpack-encoded LineItem.
type LineItemView struct {
	data []byte
	base uint32
}

// NewLineItemView creates a view over fracpack-encoded LineItem data.
// The data must be valid fracpack; call Validate() first.
func NewLineItemView(data []byte) LineItemView {
	return LineItemView{data: data, base: 0}
}

func (v LineItemView) ProductBytes() []byte { return ViewReadStr(v.data, v.base+2) }

func (v LineItemView) Product() string { return string(v.ProductBytes()) }

func (v LineItemView) Qty() uint32 { return ViewReadU32(v.data, v.base+6) }

func (v LineItemView) UnitPrice() float64 { return ViewReadF64(v.data, v.base+10) }

// SensorReadingView provides zero-copy typed access to a fracpack-encoded SensorReading.
type SensorReadingView struct {
	data []byte
	base uint32
}

// NewSensorReadingView creates a view over fracpack-encoded SensorReading data.
// The data must be valid fracpack; call Validate() first.
func NewSensorReadingView(data []byte) SensorReadingView {
	return SensorReadingView{data: data, base: 0}
}

func (v SensorReadingView) Timestamp() uint64 { return ViewReadU64(v.data, v.base+2) }

func (v SensorReadingView) DeviceIDBytes() []byte { return ViewReadStr(v.data, v.base+10) }

func (v SensorReadingView) DeviceID() string { return string(v.DeviceIDBytes()) }

func (v SensorReadingView) Temp() float64 { return ViewReadF64(v.data, v.base+14) }

func (v SensorReadingView) Humidity() float64 { return ViewReadF64(v.data, v.base+22) }

func (v SensorReadingView) Pressure() float64 { return ViewReadF64(v.data, v.base+30) }

func (v SensorReadingView) AccelX() float64 { return ViewReadF64(v.data, v.base+38) }

func (v SensorReadingView) AccelY() float64 { return ViewReadF64(v.data, v.base+46) }

func (v SensorReadingView) AccelZ() float64 { return ViewReadF64(v.data, v.base+54) }

func (v SensorReadingView) GyroX() float64 { return ViewReadF64(v.data, v.base+62) }

func (v SensorReadingView) GyroY() float64 { return ViewReadF64(v.data, v.base+70) }

func (v SensorReadingView) GyroZ() float64 { return ViewReadF64(v.data, v.base+78) }

func (v SensorReadingView) MagX() float64 { return ViewReadF64(v.data, v.base+86) }

func (v SensorReadingView) MagY() float64 { return ViewReadF64(v.data, v.base+94) }

func (v SensorReadingView) MagZ() float64 { return ViewReadF64(v.data, v.base+102) }

func (v SensorReadingView) Battery() float32 { return ViewReadF32(v.data, v.base+110) }

func (v SensorReadingView) SignalDBM() int16 { return ViewReadI16(v.data, v.base+114) }

func (v SensorReadingView) ErrorCodePresent() bool {
	return ViewReadU32(v.data, v.base+116) != 1
}

func (v SensorReadingView) ErrorCode() (uint32, bool) {
	pos := v.base + 116
	off := ViewReadU32(v.data, pos)
	if off == 1 { return 0, false }
	if off == 0 { return 0, true }
	return ViewReadU32(v.data, pos+off), true
}

func (v SensorReadingView) FirmwareBytes() []byte { return ViewReadStr(v.data, v.base+120) }

func (v SensorReadingView) Firmware() string { return string(v.FirmwareBytes()) }

// OrderView provides zero-copy typed access to a fracpack-encoded Order.
type OrderView struct {
	data []byte
	base uint32
}

// NewOrderView creates a view over fracpack-encoded Order data.
// The data must be valid fracpack; call Validate() first.
func NewOrderView(data []byte) OrderView {
	return OrderView{data: data, base: 0}
}

func (v OrderView) ID() uint64 { return ViewReadU64(v.data, v.base+2) }

func (v OrderView) Customer() UserProfileView {
	pos := v.base + 10
	off := ViewReadU32(v.data, pos)
	return UserProfileView{data: v.data, base: pos + off}
}

// OrderView.Items: unsupported kind 12 (skipped)

func (v OrderView) Total() float64 { return ViewReadF64(v.data, v.base+18) }

func (v OrderView) NotePresent() bool {
	return ViewReadU32(v.data, v.base+26) != 1
}

func (v OrderView) NoteBytes() ([]byte, bool) {
	pos := v.base + 26
	off := ViewReadU32(v.data, pos)
	if off == 1 { return nil, false }
	if off == 0 { return nil, true }
	hp := pos + off
	n := ViewReadU32(v.data, hp)
	return v.data[hp+4 : hp+4+n], true
}

