/// Cross-language fracpack test vector verification
///
/// Reads test vectors generated by the C++ gen_test_vectors tool and verifies
/// that the Rust fracpack implementation produces identical packed bytes and
/// can unpack C++-generated bytes correctly.

use fracpack::{Pack, Unpack};
use serde::Deserialize;
use std::path::Path;

// ============================================================
// Mirror types — must match the C++ definitions exactly
// ============================================================

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
#[fracpack(definition_will_not_change)]
struct FixedInts {
    x: i32,
    y: i32,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
#[fracpack(definition_will_not_change)]
struct FixedMixed {
    b: bool,
    u8_: u8,
    u16_: u16,
    u32_: u32,
    u64_: u64,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct AllPrimitives {
    b: bool,
    u8v: u8,
    i8v: i8,
    u16v: u16,
    i16v: i16,
    u32v: u32,
    i32v: i32,
    u64v: u64,
    i64v: i64,
    f32v: f32,
    f64v: f64,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
#[fracpack(definition_will_not_change)]
struct SingleBool {
    value: bool,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
#[fracpack(definition_will_not_change)]
struct SingleU32 {
    value: u32,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct SingleString {
    value: String,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct WithStrings {
    empty_str: String,
    hello: String,
    unicode: String,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct WithVectors {
    ints: Vec<u32>,
    strings: Vec<String>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct WithOptionals {
    opt_int: Option<u32>,
    opt_str: Option<String>,
}

#[derive(Pack, Unpack, PartialEq, Debug, Clone)]
#[fracpack(fracpack_mod = "fracpack")]
struct Inner {
    value: u32,
    label: String,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct Outer {
    inner: Inner,
    name: String,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
enum WithVariantData {
    #[fracpack(name = "uint32")]
    Uint32(u32),
    #[fracpack(name = "string")]
    StringAlt(String),
    Inner(Inner),
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct WithVariant {
    data: WithVariantData,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct VecOfStructs {
    items: Vec<Inner>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct OptionalStruct {
    item: Option<Inner>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct VecOfOptionals {
    items: Vec<Option<u32>>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct OptionalVec {
    items: Option<Vec<u32>>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct NestedVecs {
    matrix: Vec<Vec<u32>>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
#[fracpack(definition_will_not_change)]
struct FixedArray {
    arr: [u32; 3],
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct Complex {
    items: Vec<Inner>,
    opt_vec: Option<Vec<u32>>,
    vec_opt: Vec<Option<String>>,
    opt_struct: Option<Inner>,
}

#[derive(Pack, Unpack, PartialEq, Debug)]
#[fracpack(fracpack_mod = "fracpack")]
struct EmptyExtensible {
    dummy: u32,
}

// ============================================================
// Test vector JSON schema
// ============================================================

#[derive(Deserialize)]
struct TestVectors {
    #[allow(dead_code)]
    format_version: u32,
    types: Vec<TypeGroup>,
}

#[derive(Deserialize)]
struct TypeGroup {
    name: String,
    #[allow(dead_code)]
    schema: serde_json::Value,
    #[allow(dead_code)]
    schema_hex: String,
    #[allow(dead_code)]
    root_type: String,
    cases: Vec<TestCase>,
}

#[derive(Deserialize)]
struct TestCase {
    name: String,
    packed_hex: String,
    json: serde_json::Value,
}

// ============================================================
// Helpers
// ============================================================

fn to_hex(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("{:02X}", b))
        .collect::<String>()
}

fn from_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn load_vectors() -> TestVectors {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("test_vectors/vectors.json");
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
    serde_json::from_str(&content).expect("Failed to parse vectors.json")
}

fn find_group<'a>(vectors: &'a TestVectors, name: &str) -> &'a TypeGroup {
    vectors
        .types
        .iter()
        .find(|g| g.name == name)
        .unwrap_or_else(|| panic!("Type group '{}' not found in vectors.json", name))
}

/// Verify that packing a Rust value produces the same hex as C++
fn verify_pack<T: Pack>(value: &T, expected_hex: &str, context: &str) {
    let packed = value.packed();
    let actual_hex = to_hex(&packed);
    assert_eq!(
        actual_hex, expected_hex,
        "{}: pack mismatch\n  Rust:  {}\n  C++:   {}",
        context, actual_hex, expected_hex
    );
}

/// Verify that unpacking C++ bytes produces a value that re-packs to the same bytes
fn verify_unpack_roundtrip<'a, T: Unpack<'a> + Pack + std::fmt::Debug>(
    cpp_bytes: &'a [u8],
    context: &str,
) {
    let unpacked = T::unpacked(cpp_bytes)
        .unwrap_or_else(|e| panic!("{}: unpack failed: {}", context, e));
    let repacked = unpacked.packed();
    assert_eq!(
        repacked, cpp_bytes,
        "{}: roundtrip mismatch\n  original:  {}\n  repacked:  {}\n  unpacked: {:?}",
        context,
        to_hex(cpp_bytes),
        to_hex(&repacked),
        unpacked,
    );
}

// ============================================================
// Type-specific test runners
// ============================================================

macro_rules! vector_test {
    ($test_name:ident, $type_name:expr, $rust_type:ty, $cases:expr) => {
        #[test]
        fn $test_name() {
            let vectors = load_vectors();
            let group = find_group(&vectors, $type_name);

            // Verify pack from known Rust values
            let cases: Vec<(&str, $rust_type)> = $cases;
            for (case_name, value) in &cases {
                let tc = group
                    .cases
                    .iter()
                    .find(|c| c.name == *case_name)
                    .unwrap_or_else(|| panic!("Case '{}' not found", case_name));
                let ctx = format!("{}::{}", $type_name, case_name);
                verify_pack(value, &tc.packed_hex, &ctx);
            }

            // Verify unpack of ALL C++ vectors (even ones we don't have Rust values for)
            for tc in &group.cases {
                let ctx = format!("{}::{}", $type_name, tc.name);
                let cpp_bytes = from_hex(&tc.packed_hex);
                verify_unpack_roundtrip::<$rust_type>(&cpp_bytes, &ctx);
            }
        }
    };
}

// ============================================================
// Tests
// ============================================================

vector_test!(test_fixed_ints, "FixedInts", FixedInts, vec![
    ("zeros", FixedInts { x: 0, y: 0 }),
    ("positive", FixedInts { x: 42, y: 100 }),
    ("negative", FixedInts { x: -1, y: -2147483648 }),
    ("max", FixedInts { x: 2147483647, y: 2147483647 }),
]);

vector_test!(test_fixed_mixed, "FixedMixed", FixedMixed, vec![
    ("zeros", FixedMixed { b: false, u8_: 0, u16_: 0, u32_: 0, u64_: 0 }),
    ("ones", FixedMixed { b: true, u8_: 1, u16_: 1, u32_: 1, u64_: 1 }),
    ("max", FixedMixed { b: true, u8_: 255, u16_: 65535, u32_: u32::MAX, u64_: u64::MAX }),
]);

vector_test!(test_all_primitives, "AllPrimitives", AllPrimitives, vec![
    ("zeros", AllPrimitives {
        b: false, u8v: 0, i8v: 0, u16v: 0, i16v: 0,
        u32v: 0, i32v: 0, u64v: 0, i64v: 0, f32v: 0.0, f64v: 0.0
    }),
    ("ones", AllPrimitives {
        b: true, u8v: 1, i8v: 1, u16v: 1, i16v: 1,
        u32v: 1, i32v: 1, u64v: 1, i64v: 1, f32v: 1.0, f64v: 1.0
    }),
]);

vector_test!(test_single_bool, "SingleBool", SingleBool, vec![
    ("false", SingleBool { value: false }),
    ("true", SingleBool { value: true }),
]);

vector_test!(test_single_u32, "SingleU32", SingleU32, vec![
    ("zero", SingleU32 { value: 0 }),
    ("one", SingleU32 { value: 1 }),
    ("max", SingleU32 { value: u32::MAX }),
    ("hex_pattern", SingleU32 { value: 0xDEADBEEF }),
]);

vector_test!(test_single_string, "SingleString", SingleString, vec![
    ("empty", SingleString { value: "".into() }),
    ("hello", SingleString { value: "hello".into() }),
    ("with_spaces", SingleString { value: "hello world".into() }),
    ("special_chars", SingleString { value: "tab\there\nnewline".into() }),
    ("unicode", SingleString { value: "caf\u{e9} \u{2615} \u{65e5}\u{672c}\u{8a9e}".into() }),
    ("escapes", SingleString { value: "quote\"backslash\\".into() }),
]);

vector_test!(test_with_strings, "WithStrings", WithStrings, vec![
    ("all_empty", WithStrings { empty_str: "".into(), hello: "".into(), unicode: "".into() }),
    ("mixed", WithStrings {
        empty_str: "".into(),
        hello: "hello".into(),
        unicode: "\u{e9}mojis: \u{1f389}\u{1f680}".into()
    }),
]);

vector_test!(test_with_vectors, "WithVectors", WithVectors, vec![
    ("both_empty", WithVectors { ints: vec![], strings: vec![] }),
    ("ints_only", WithVectors { ints: vec![1, 2, 3], strings: vec![] }),
    ("strings_only", WithVectors { ints: vec![], strings: vec!["a".into(), "bb".into(), "ccc".into()] }),
    ("both_filled", WithVectors { ints: vec![10, 20], strings: vec!["hello".into(), "world".into()] }),
    ("single_elements", WithVectors { ints: vec![42], strings: vec!["only".into()] }),
]);

vector_test!(test_with_optionals, "WithOptionals", WithOptionals, vec![
    ("both_null", WithOptionals { opt_int: None, opt_str: None }),
    ("int_only", WithOptionals { opt_int: Some(42), opt_str: None }),
    ("str_only", WithOptionals { opt_int: None, opt_str: Some("hello".into()) }),
    ("both_present", WithOptionals { opt_int: Some(99), opt_str: Some("world".into()) }),
    ("zero_int", WithOptionals { opt_int: Some(0), opt_str: None }),
]);

vector_test!(test_inner, "Inner", Inner, vec![
    ("simple", Inner { value: 42, label: "hello".into() }),
    ("empty_label", Inner { value: 0, label: "".into() }),
    ("max_value", Inner { value: u32::MAX, label: "max".into() }),
]);

vector_test!(test_outer, "Outer", Outer, vec![
    ("simple", Outer { inner: Inner { value: 1, label: "inner".into() }, name: "outer".into() }),
    ("empty_strings", Outer { inner: Inner { value: 0, label: "".into() }, name: "".into() }),
    ("nested_unicode", Outer {
        inner: Inner { value: 42, label: "caf\u{e9}".into() },
        name: "na\u{ef}ve".into()
    }),
]);

vector_test!(test_vec_of_structs, "VecOfStructs", VecOfStructs, vec![
    ("empty", VecOfStructs { items: vec![] }),
    ("single", VecOfStructs { items: vec![Inner { value: 1, label: "one".into() }] }),
    ("multiple", VecOfStructs {
        items: vec![
            Inner { value: 1, label: "one".into() },
            Inner { value: 2, label: "two".into() },
            Inner { value: 3, label: "three".into() },
        ]
    }),
]);

vector_test!(test_optional_struct, "OptionalStruct", OptionalStruct, vec![
    ("null", OptionalStruct { item: None }),
    ("present", OptionalStruct { item: Some(Inner { value: 42, label: "exists".into() }) }),
]);

vector_test!(test_vec_of_optionals, "VecOfOptionals", VecOfOptionals, vec![
    ("empty", VecOfOptionals { items: vec![] }),
    ("all_null", VecOfOptionals { items: vec![None, None, None] }),
    ("all_present", VecOfOptionals { items: vec![Some(1), Some(2), Some(3)] }),
    ("mixed", VecOfOptionals { items: vec![Some(1), None, Some(3), None] }),
]);

vector_test!(test_optional_vec, "OptionalVec", OptionalVec, vec![
    ("null", OptionalVec { items: None }),
    ("empty_vec", OptionalVec { items: Some(vec![]) }),
    ("with_values", OptionalVec { items: Some(vec![10, 20, 30]) }),
]);

vector_test!(test_nested_vecs, "NestedVecs", NestedVecs, vec![
    ("empty", NestedVecs { matrix: vec![] }),
    ("empty_rows", NestedVecs { matrix: vec![vec![], vec![], vec![]] }),
    ("identity_2x2", NestedVecs { matrix: vec![vec![1, 0], vec![0, 1]] }),
    ("ragged", NestedVecs { matrix: vec![vec![1], vec![2, 3], vec![4, 5, 6]] }),
]);

vector_test!(test_fixed_array, "FixedArray", FixedArray, vec![
    ("zeros", FixedArray { arr: [0, 0, 0] }),
    ("sequence", FixedArray { arr: [1, 2, 3] }),
    ("max", FixedArray { arr: [u32::MAX, u32::MAX, u32::MAX] }),
]);

vector_test!(test_complex, "Complex", Complex, vec![
    ("all_empty", Complex {
        items: vec![],
        opt_vec: None,
        vec_opt: vec![],
        opt_struct: None,
    }),
    ("all_populated", Complex {
        items: vec![Inner { value: 1, label: "a".into() }, Inner { value: 2, label: "b".into() }],
        opt_vec: Some(vec![10, 20]),
        vec_opt: vec![Some("x".into()), None, Some("z".into())],
        opt_struct: Some(Inner { value: 99, label: "present".into() }),
    }),
    ("sparse", Complex {
        items: vec![Inner { value: 42, label: "only".into() }],
        opt_vec: None,
        vec_opt: vec![None, None],
        opt_struct: None,
    }),
]);

vector_test!(test_with_variant, "WithVariant", WithVariant, vec![
    ("uint32_alt", WithVariant { data: WithVariantData::Uint32(42) }),
    ("string_alt", WithVariant { data: WithVariantData::StringAlt("hello".into()) }),
    ("struct_alt", WithVariant { data: WithVariantData::Inner(Inner { value: 7, label: "variant_inner".into() }) }),
    ("uint32_zero", WithVariant { data: WithVariantData::Uint32(0) }),
    ("string_empty", WithVariant { data: WithVariantData::StringAlt("".into()) }),
]);

vector_test!(test_empty_extensible, "EmptyExtensible", EmptyExtensible, vec![
    ("zero", EmptyExtensible { dummy: 0 }),
    ("max", EmptyExtensible { dummy: u32::MAX }),
]);
