#pragma once

// Structural-metadata macros: declarative WIT package + interface registration.
//
//   PSIO_PACKAGE(name, version)              — declares a WIT package
//   PSIO_INTERFACE(Tag, types(…), funcs(…))  — registers an interface
//   PSIO_USE(package, interface, version)    — cross-package use
//   PSIO_WORLD(name, imports(…), exports(…)) — top-level composition
//   PSIO_HOST_MODULE(Impl, interface(Tag, m…)…) — bind C++ host impl
//
// Each macro populates a compile-time, tag-keyed registry. wit_gen and
// wit_constexpr walk those registries to assemble WIT text or binary.
//
// Interface tags are user-authored types: the same struct/class that
// declares the interface's static member functions is used directly as
// the tag — no separate `*_interface_tag` helper.
//
// Usage:
//
//   PSIO_PACKAGE(wasi_clocks, "0.2.3");
//   #undef  PSIO_CURRENT_PACKAGE_
//   #define PSIO_CURRENT_PACKAGE_ PSIO_PACKAGE_TYPE_(wasi_clocks)
//
//   struct wasi_clocks_wall_clock {
//       static datetime now();
//       static datetime resolution();
//   };
//   PSIO_INTERFACE(wasi_clocks_wall_clock,
//                  types(datetime),
//                  funcs(func(now), func(resolution)))
//
// PSIO_CURRENT_PACKAGE_ must be redefined after each PSIO_PACKAGE call —
// `#define` cannot appear inside a macro expansion, so the redefine is
// part of the user-facing pattern.
//
// Internals: package_info<TagStruct> and interface_info<Tag> are
// specialized inside namespace psio::detail. A unique tag struct per
// package is generated by the macro (NAME##_pkg_tag), avoiding the
// FixedString non-type-template-parameter pattern v1 used (v3 elects to
// keep names as runtime const char* / string_view and reserve type
// identity for tag types).

#include <psio/reflect.hpp>  // brings in BOOST_PP and the existing PSIO_PP_* helpers

#include <array>
#include <string_view>
#include <tuple>

#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/transform.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/seq/to_tuple.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/push_front.hpp>
#include <boost/preprocessor/tuple/rem.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include <boost/preprocessor/variadic/size.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/facilities/check_empty.hpp>

// =====================================================================
// Preprocessor utilities specific to structural.hpp
//
// reflect.hpp already provides PSIO_PP_FIRST / PSIO_PP_APPLY_FIRST /
// PSIO_PP_MATCH. The helpers below cover what structural.hpp also
// needs: empty no-op, paren removal, seq→va_args, the funcs() entry
// grammar (`func(ident, args...)`), and boost-PP wrappers that tolerate
// empty sequences.
// =====================================================================

#define PSIO_PP_EMPTY(...)
#define PSIO_PP_REMOVE_PARENS(...) BOOST_PP_TUPLE_REM() __VA_ARGS__
#define PSIO_PP_SEQ_TO_VA_ARGS(seq) PSIO_PP_REMOVE_PARENS(BOOST_PP_SEQ_TO_TUPLE(seq))

// Seq variants that survive an empty sequence (BOOST_PP versions choke).
#define PSIO_PP_SEQ_TRANSFORM(op, data, seq) \
   BOOST_PP_IIF(BOOST_PP_CHECK_EMPTY(seq), PSIO_PP_EMPTY, BOOST_PP_SEQ_TRANSFORM)(op, data, seq)

#define PSIO_PP_SEQ_FILTER(op, data, seq) \
   BOOST_PP_IIF(BOOST_PP_CHECK_EMPTY(seq), PSIO_PP_EMPTY, BOOST_PP_SEQ_FILTER)(op, data, seq)

// =====================================================================
// funcs(...) entry grammar
//
// Each entry inside funcs(...) is either a bare identifier (e.g. `now`)
// or the canonical `func(ident, p1, p2, ...)` form (e.g.
// `func(subscribe_instant, when)`). Both normalize to the internal
// `_psio_method(ident, args...)` shape so the same downstream helpers
// apply uniformly.
// =====================================================================

#define PSIO_IFACE_MATCH_func(...) ~, 1
#define PSIO_IFACE_ARGS_func(...)  __VA_ARGS__

#define PSIO_IFACE_NORMALIZE_ENTRY(r, _, item)                               \
   BOOST_PP_IIF(                                                             \
       BOOST_PP_CHECK_EMPTY(item), ,                                         \
       BOOST_PP_IIF(PSIO_PP_MATCH(PSIO_IFACE_MATCH_, item),                  \
                    PSIO_IFACE_NORMALIZE_MATCHED,                            \
                    PSIO_IFACE_NORMALIZE_BARE)(item))

#define PSIO_IFACE_NORMALIZE_MATCHED(item) \
   _psio_method(BOOST_PP_CAT(PSIO_IFACE_ARGS_, item))
#define PSIO_IFACE_NORMALIZE_BARE(item) _psio_method(item)

// _psio_method(ident, args...) → ident
#define PSIO_IFACE_GET_IDENT(elem)         BOOST_PP_CAT(PSIO_IFACE_GET_IDENT_, elem)
#define PSIO_IFACE_GET_IDENT__psio_method(ident, ...) ident

// _psio_method(ident, args...) → args... (or nothing if no args)
#define PSIO_IFACE_GET_ARGS(elem)          BOOST_PP_CAT(PSIO_IFACE_GET_ARGS_, elem)
#define PSIO_IFACE_GET_ARGS__psio_method(ident, ...) __VA_ARGS__

// _psio_method(ident, a, b) → "a", "b"  (empty if no args)
#define PSIO_IFACE_QUOTED_ARGS(elem)                                              \
   BOOST_PP_IIF(BOOST_PP_CHECK_EMPTY(PSIO_IFACE_GET_ARGS(elem)),                  \
                PSIO_PP_EMPTY,                                                    \
                PSIO_IFACE_QUOTED_ARGS_IMPL)(elem)
#define PSIO_IFACE_QUOTED_ARGS_IMPL(elem)                                         \
   PSIO_PP_SEQ_TO_VA_ARGS(BOOST_PP_SEQ_TRANSFORM(                                 \
       PSIO_IFACE_QUOTE_ONE, _, BOOST_PP_VARIADIC_TO_SEQ(PSIO_IFACE_GET_ARGS(elem))))
#define PSIO_IFACE_QUOTE_ONE(r, _, arg) BOOST_PP_STRINGIZE(arg)

// =====================================================================
// types(...) and funcs(...) wrappers — strip the keyword shell.
// =====================================================================

#define PSIO_IFACE_UNWRAP_TYPES(X)         BOOST_PP_CAT(PSIO_IFACE_UNWRAP_TYPES_, X)
#define PSIO_IFACE_UNWRAP_TYPES_types(...) __VA_ARGS__

#define PSIO_IFACE_UNWRAP_FUNCS(X)         BOOST_PP_CAT(PSIO_IFACE_UNWRAP_FUNCS_, X)
#define PSIO_IFACE_UNWRAP_FUNCS_funcs(...) __VA_ARGS__

// =====================================================================
// Per-entry expansion helpers
//
// Reflection only inspects the *type* of each interface method, not
// its address: decltype(&ANCHOR::m) is unevaluated and does not ODR-use
// the function, so the anchor struct may declare static methods with
// no inline bodies if desired (host-side bodies live wherever).
// =====================================================================

#define PSIO_IFACE_FN_TYPE(r, ANCHOR, elem) \
   decltype(&ANCHOR::PSIO_IFACE_GET_IDENT(elem))
#define PSIO_IFACE_FN_NAME(r, _, elem) \
   BOOST_PP_STRINGIZE(PSIO_IFACE_GET_IDENT(elem))
#define PSIO_IFACE_PARAM_NAMES_ENTRY(r, _, elem) \
   ::std::initializer_list<const char*>{PSIO_IFACE_QUOTED_ARGS(elem)},

// Reverse-lookup specialization, emitted per type listed in `types(...)`.
#define PSIO_IFACE_REV_LOOKUP(s, TAG, T)                  \
   template <>                                            \
   struct ::psio::interface_of<T>                         \
   {                                                      \
      using type = TAG;                                   \
   };

namespace psio
{

// ─── Reverse lookup: T → owning interface tag ────────────────────────
//
// Specialized by PSIO_INTERFACE for every T listed in its types(…)
// argument. Undefined for interface-less types — schema-walking code
// uses that fact to detect "this is a raw reflected value, not an
// interface-owned one."
template <typename T>
struct interface_of;

// Reverse lookup: ImplClass → tuple of interface tags it implements.
// Specialized by PSIO_HOST_MODULE.  The Linker uses this in
// `provide(impl)` to find all slots that a host implementation fills.
template <typename ImplClass>
struct impl_of;

namespace detail
{

// ─── Package registry ─────────────────────────────────────────────────
//
// PSIO_PACKAGE(NAME, VERSION) generates `struct NAME##_pkg_tag {};`
// alongside `package_info<NAME##_pkg_tag>` carrying the name and
// version strings. PSIO_CURRENT_PACKAGE_ resolves to the
// specialization, so consumers spell `package_info<...>` directly via
// `using package = PSIO_CURRENT_PACKAGE_;` inside PSIO_INTERFACE.
template <typename Tag>
struct package_info;

template <typename Tag>
struct package_marker
{
};

// ─── Interface registry ───────────────────────────────────────────────
//
// PSIO_INTERFACE(Tag, types(...), funcs(...)) specializes
// interface_info<Tag>. The Tag is the user's interface class itself
// (the one carrying static member functions for the operations).
//
// Exposed surface:
//   ::name        — string_view, source-spelled interface identifier
//   ::package     — the PSIO_CURRENT_PACKAGE_ specialization at the
//                   point of expansion
//   ::types       — std::tuple<T1, T2, ...> from types(...)
//   ::func_types  — std::tuple<decltype(&Tag::m1), ...>
//   ::func_names  — std::array<string_view, N>
//   ::param_names — initializer_list<const char*>[N]
template <typename Tag>
struct interface_info;

template <typename Tag>
struct interface_marker
{
};

// ─── Cross-package use registry — specialized by PSIO_USE ──────────
template <typename Tag>
struct use_info;

template <typename Tag>
struct use_marker
{
};

// ─── World registry — specialized by PSIO_WORLD ───────────────────
template <typename Tag>
struct world_info;

template <typename Tag>
struct world_marker
{
};

// ─── Per-(Impl, Tag) registry — one specialization per `interface(...)`
// entry inside PSIO_HOST_MODULE.  Carries:
//   ::host    = ImplClass
//   ::tag     = interface tag
//   ::methods = std::tuple<&Impl::m1, &Impl::m2, …>
//   ::names   = std::array<string_view, N>{"m1", "m2", …}
template <typename ImplClass, typename Tag>
struct iface_impl;

// Aggregate per-Impl registry — specialized by PSIO_HOST_MODULE.
// Carries the tuple of iface_impl<Impl, Tag> instantiations.
template <typename ImplClass>
struct impl_info;

// Variadic helper: PSIO_HOST_MODULE only emits a parenthesis-friendly
// list of tag types and the template machinery assembles
// `iface_impl<Impl, Tag>` tuples.  Avoids Boost.PP's struggle with
// commas inside `< >`.
template <typename Impl, typename... Tags>
using iface_impls_tuple = ::std::tuple<iface_impl<Impl, Tags>...>;

}  // namespace detail

// Convenience: T → package, transitively via interface_of.
template <typename T>
struct package_of
{
   using interface_tag        = typename interface_of<T>::type;
   using package              = typename detail::interface_info<interface_tag>::package;
   static constexpr auto name = package::name;
};

}  // namespace psio

// =====================================================================
// PSIO_PACKAGE(NAME, VERSION)
// =====================================================================

// Sentinel — overwritten by the first user PSIO_PACKAGE / #define pair.
#define PSIO_CURRENT_PACKAGE_ void

#define PSIO_PACKAGE_TYPE_(NAME) \
   ::psio::detail::package_info<::psio::detail::NAME##_pkg_tag>

#define PSIO_PACKAGE(NAME, VERSION)                                          \
   namespace psio::detail                                                    \
   {                                                                         \
      struct NAME##_pkg_tag                                                  \
      {                                                                      \
      };                                                                     \
      template <>                                                            \
      struct package_info<NAME##_pkg_tag>                                    \
      {                                                                      \
         static constexpr ::std::string_view name    = #NAME;                \
         static constexpr ::std::string_view version = VERSION;              \
      };                                                                     \
      inline constexpr package_marker<NAME##_pkg_tag> _psio_pkg_##NAME{};    \
   }
// !! After PSIO_PACKAGE, you MUST also write:
//     #undef  PSIO_CURRENT_PACKAGE_
//     #define PSIO_CURRENT_PACKAGE_ PSIO_PACKAGE_TYPE_(NAME)
// to bind subsequent PSIO_INTERFACE calls to this package. The C
// preprocessor disallows #define inside macro expansion, so this step
// is part of the user-facing pattern.

// =====================================================================
// PSIO_INTERFACE(Tag, types(...), funcs(...))
// =====================================================================

#define PSIO_INTERFACE(NAME, TYPES_SPEC, FUNCS_SPEC)                                  \
   BOOST_PP_IIF(BOOST_PP_CHECK_EMPTY(PSIO_IFACE_UNWRAP_TYPES(TYPES_SPEC)),            \
                PSIO_INTERFACE_NO_TYPES,                                              \
                PSIO_INTERFACE_WITH_TYPES)(NAME, TYPES_SPEC, FUNCS_SPEC)

#define PSIO_INTERFACE_WITH_TYPES(NAME, TYPES_SPEC, FUNCS_SPEC)                       \
   PSIO_INTERFACE_BODY(NAME,                                                          \
                       ::std::tuple<PSIO_IFACE_UNWRAP_TYPES(TYPES_SPEC)>,             \
                       BOOST_PP_SEQ_TRANSFORM(                                        \
                           PSIO_IFACE_NORMALIZE_ENTRY, _,                             \
                           BOOST_PP_VARIADIC_TO_SEQ(                                  \
                               PSIO_IFACE_UNWRAP_FUNCS(FUNCS_SPEC))))                 \
   BOOST_PP_SEQ_FOR_EACH(PSIO_IFACE_REV_LOOKUP, ::NAME,                               \
                         BOOST_PP_VARIADIC_TO_SEQ(                                    \
                             PSIO_IFACE_UNWRAP_TYPES(TYPES_SPEC)))

#define PSIO_INTERFACE_NO_TYPES(NAME, TYPES_SPEC, FUNCS_SPEC)                         \
   PSIO_INTERFACE_BODY(NAME,                                                          \
                       ::std::tuple<>,                                                \
                       BOOST_PP_SEQ_TRANSFORM(                                        \
                           PSIO_IFACE_NORMALIZE_ENTRY, _,                             \
                           BOOST_PP_VARIADIC_TO_SEQ(                                  \
                               PSIO_IFACE_UNWRAP_FUNCS(FUNCS_SPEC))))

#define PSIO_INTERFACE_BODY(NAME, TYPES_TUPLE, FUNCS_SEQ)                             \
   namespace psio::detail                                                             \
   {                                                                                  \
      template <>                                                                     \
      struct interface_info<::NAME>                                                   \
      {                                                                               \
         static constexpr ::std::string_view name = #NAME;                            \
         using package    = PSIO_CURRENT_PACKAGE_;                                    \
         using types      = TYPES_TUPLE;                                              \
         using func_types = ::std::tuple<PSIO_PP_SEQ_TO_VA_ARGS(                      \
             BOOST_PP_SEQ_TRANSFORM(PSIO_IFACE_FN_TYPE, ::NAME, FUNCS_SEQ))>;         \
         static constexpr ::std::array<::std::string_view,                            \
                                       BOOST_PP_SEQ_SIZE(FUNCS_SEQ)>                  \
             func_names{PSIO_PP_SEQ_TO_VA_ARGS(                                       \
                 BOOST_PP_SEQ_TRANSFORM(PSIO_IFACE_FN_NAME, _, FUNCS_SEQ))};          \
         static constexpr ::std::initializer_list<const char*>                        \
             param_names[BOOST_PP_SEQ_SIZE(FUNCS_SEQ)] = {                            \
                 BOOST_PP_SEQ_FOR_EACH(PSIO_IFACE_PARAM_NAMES_ENTRY, _, FUNCS_SEQ)};  \
      };                                                                              \
      inline constexpr interface_marker<::NAME>                                       \
          BOOST_PP_CAT(_psio_iface_, NAME){};                                         \
   }

// =====================================================================
// PSIO_USE(PACKAGE, INTERFACE, VERSION) — cross-package interface use
// =====================================================================
//
// Records that the current scope wants to depend on a specific
// (PACKAGE, INTERFACE) at a given version.  Schema-walking and Linker
// code consumes this to compose worlds out of pre-existing interfaces.
//
// Example:
//
//   PSIO_USE(wasi_io, poll, "0.2.3")
//
// generates a unique tag struct and `use_info<Tag>` carrying the
// three string_views.  The tag's name is `<PACKAGE>_<INTERFACE>_use_tag`.

#define PSIO_USE_TAG_(PACKAGE, INTERFACE) \
   BOOST_PP_CAT(BOOST_PP_CAT(PACKAGE, _), BOOST_PP_CAT(INTERFACE, _use_tag))

#define PSIO_USE(PACKAGE, INTERFACE, VERSION)                                          \
   namespace psio::detail                                                              \
   {                                                                                   \
      struct PSIO_USE_TAG_(PACKAGE, INTERFACE)                                         \
      {                                                                                \
      };                                                                               \
      template <>                                                                      \
      struct use_info<PSIO_USE_TAG_(PACKAGE, INTERFACE)>                                \
      {                                                                                \
         static constexpr ::std::string_view package        = #PACKAGE;                \
         static constexpr ::std::string_view interface_name = #INTERFACE;              \
         static constexpr ::std::string_view version        = VERSION;                 \
      };                                                                               \
      inline constexpr use_marker<PSIO_USE_TAG_(PACKAGE, INTERFACE)>                    \
          BOOST_PP_CAT(BOOST_PP_CAT(_psio_use_, PACKAGE),                              \
                       BOOST_PP_CAT(_, INTERFACE)){};                                  \
   }

// =====================================================================
// PSIO_WORLD(NAME, imports(...), exports(...)) — top-level composition
// =====================================================================
//
// `imports(…)` lists use-tags (see PSIO_USE) and/or interface tags;
// `exports(…)` lists interface tags.  Both sides accept bare-name lists
// — no `func()` wrapping needed (worlds compose interfaces, not
// functions).
//
// The expansion lives in `namespace psio::detail`, so unqualified
// names are resolved via the chain  detail → psio → ::  — user
// classes at global scope are picked up through the global fallback.

#define PSIO_WORLD_UNWRAP_IMPORTS(X)         BOOST_PP_CAT(PSIO_WORLD_UNWRAP_IMPORTS_, X)
#define PSIO_WORLD_UNWRAP_IMPORTS_imports(...) __VA_ARGS__

#define PSIO_WORLD_UNWRAP_EXPORTS(X)         BOOST_PP_CAT(PSIO_WORLD_UNWRAP_EXPORTS_, X)
#define PSIO_WORLD_UNWRAP_EXPORTS_exports(...) __VA_ARGS__

#define PSIO_WORLD(NAME, IMPORTS_SPEC, EXPORTS_SPEC) \
   PSIO_WORLD_I_(NAME, PSIO_WORLD_UNWRAP_IMPORTS(IMPORTS_SPEC),  \
                       PSIO_WORLD_UNWRAP_EXPORTS(EXPORTS_SPEC))

#define PSIO_WORLD_I_(NAME, IMPORTS_VA, EXPORTS_VA)                                    \
   namespace psio::detail                                                              \
   {                                                                                   \
      struct BOOST_PP_CAT(NAME, _world_tag)                                            \
      {                                                                                \
      };                                                                               \
      template <>                                                                      \
      struct world_info<BOOST_PP_CAT(NAME, _world_tag)>                                \
      {                                                                                \
         static constexpr ::std::string_view name = #NAME;                             \
         using package = PSIO_CURRENT_PACKAGE_;                                        \
         using imports = ::std::tuple<IMPORTS_VA>;                                     \
         using exports = ::std::tuple<EXPORTS_VA>;                                     \
      };                                                                               \
      inline constexpr world_marker<BOOST_PP_CAT(NAME, _world_tag)>                    \
          BOOST_PP_CAT(_psio_world_, NAME){};                                          \
   }

// =====================================================================
// PSIO_HOST_MODULE(IMPL, interface(Tag, m1, m2, …)…) — bind C++ impl
// =====================================================================
//
// Declares ImplClass as the host implementation of one or more
// interfaces.  Each entry `interface(Tag, m1, m2, …)` lists the
// interface's tag and the member functions on Impl that fulfill it,
// in the same order as the interface's PSIO_INTERFACE funcs(…) entries.
//
// Effects:
//   • iface_impl<Impl, Tag> is specialized for each entry
//     (::tag / ::methods / ::names).
//   • impl_info<Impl> is specialized with ::interfaces =
//     iface_impls_tuple<Impl, Tag1, Tag2, …>.
//   • impl_of<Impl>::type = std::tuple<Tag1, Tag2, …> for Linker
//     reverse lookup.
//
// Must appear at namespace scope.  At least one entry is required.

#define PSIO_HOST_MODULE_ARGS_interface(...) __VA_ARGS__

#define PSIO_HOST_MODULE_HEAD_(x, ...) x
#define PSIO_HOST_MODULE_TAIL_(x, ...) __VA_ARGS__

#define PSIO_HOST_MODULE_TAG_(entry) \
   PSIO_HOST_MODULE_TAG_I_(BOOST_PP_CAT(PSIO_HOST_MODULE_ARGS_, entry))
#define PSIO_HOST_MODULE_TAG_I_(...) PSIO_HOST_MODULE_HEAD_(__VA_ARGS__)

#define PSIO_HOST_MODULE_METHODS_(entry) \
   PSIO_HOST_MODULE_METHODS_I_(BOOST_PP_CAT(PSIO_HOST_MODULE_ARGS_, entry))
#define PSIO_HOST_MODULE_METHODS_I_(...) PSIO_HOST_MODULE_TAIL_(__VA_ARGS__)

#define PSIO_HOST_MODULE_METHODS_SEQ_(entry) \
   BOOST_PP_VARIADIC_TO_SEQ(PSIO_HOST_MODULE_METHODS_(entry))

#define PSIO_HOST_MODULE_MEMBER_PTR_(s, IMPL, METHOD) &IMPL::METHOD
#define PSIO_HOST_MODULE_NAME_(s, _, METHOD)          BOOST_PP_STRINGIZE(METHOD)

#define PSIO_HOST_MODULE_EMIT_ENTRY_(r, IMPL, entry)                                   \
   template <>                                                                         \
   struct ::psio::detail::iface_impl<IMPL, ::PSIO_HOST_MODULE_TAG_(entry)>              \
   {                                                                                   \
      using host = IMPL;                                                               \
      using tag  = ::PSIO_HOST_MODULE_TAG_(entry);                                      \
      static constexpr auto methods = ::std::tuple{PSIO_PP_SEQ_TO_VA_ARGS(             \
         BOOST_PP_SEQ_TRANSFORM(PSIO_HOST_MODULE_MEMBER_PTR_, IMPL,                    \
                                PSIO_HOST_MODULE_METHODS_SEQ_(entry)))};               \
      static constexpr ::std::array<                                                   \
         ::std::string_view,                                                           \
         BOOST_PP_SEQ_SIZE(PSIO_HOST_MODULE_METHODS_SEQ_(entry))>                       \
         names{PSIO_PP_SEQ_TO_VA_ARGS(                                                 \
            BOOST_PP_SEQ_TRANSFORM(PSIO_HOST_MODULE_NAME_, _,                          \
                                   PSIO_HOST_MODULE_METHODS_SEQ_(entry)))};            \
   };

#define PSIO_HOST_MODULE_TAG_TYPE_(s, _, entry) ::PSIO_HOST_MODULE_TAG_(entry)

#define PSIO_HOST_MODULE(IMPL, ...)                                                    \
   BOOST_PP_SEQ_FOR_EACH(PSIO_HOST_MODULE_EMIT_ENTRY_, IMPL,                            \
                         BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))                        \
   template <>                                                                         \
   struct ::psio::impl_of<IMPL>                                                        \
   {                                                                                   \
      using type = ::std::tuple<PSIO_PP_SEQ_TO_VA_ARGS(                                \
         BOOST_PP_SEQ_TRANSFORM(PSIO_HOST_MODULE_TAG_TYPE_, _,                         \
                                BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))>;              \
   };                                                                                  \
   template <>                                                                         \
   struct ::psio::detail::impl_info<IMPL>                                              \
   {                                                                                   \
      using interfaces = ::psio::detail::iface_impls_tuple<IMPL,                        \
         PSIO_PP_SEQ_TO_VA_ARGS(                                                       \
            BOOST_PP_SEQ_TRANSFORM(PSIO_HOST_MODULE_TAG_TYPE_, _,                      \
                                   BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__)))>;           \
   };
