#pragma once

/// @file wit_resource.hpp
/// @brief WIT Component Model resource types for C++ ↔ WASM boundaries.
///
/// # Overview
///
/// WIT resources are opaque handle types that cross the WASM component boundary
/// as u32 indices into a per-component handle table. This header provides the
/// C++ vocabulary types that the PSIO reflection and WIT generation system uses
/// to express resource ownership semantics.
///
/// # Architecture
///
/// There are three roles in the resource system:
///
/// ## 1. The shared interface header (used by both host and guest)
///
///    Declares the resource type's method signatures and reflects them:
///
///       struct cursor : psio::wit_resource {
///           bool                 seek(std::vector<uint8_t> key);
///           bool                 next();
///           std::vector<uint8_t> key() const;
///           std::vector<uint8_t> value() const;
///       };
///       PSIO_REFLECT(cursor, method(seek, key), method(next),
///                    method(key), method(value))
///
///    Inheriting from `wit_resource` signals to the WIT generator that this
///    type should be emitted as a `resource` block (with methods), not as a
///    `record` (with data fields). Data members are ignored in WIT output —
///    resources are opaque across the boundary.
///
/// ## 2. The host side (real implementation)
///
///    Derives from the shared interface to provide the actual logic:
///
///       struct cursor_impl : cursor {
///           db_handle db_;
///           iterator  it_;
///           bool seek(std::vector<uint8_t> key) override { /* ... */ }
///           // ...
///       };
///
///    The runtime maintains a handle_table<cursor_impl> that maps u32 handles
///    to live instances. When WASM calls [method]cursor.seek, the runtime:
///      1. Extracts the u32 handle from the WASM stack
///      2. Looks up cursor_impl* in the handle table
///      3. Calls cursor_impl::seek() with the remaining arguments
///      4. Returns the result to WASM
///
/// ## 3. The guest side (proxy over imports)
///
///    The guest never defines resource types — it receives them. The guest sees
///    own<cursor> and borrow<cursor> as RAII wrappers:
///
///       void process(psio::borrow<cursor> c) {
///           while (c->next()) {
///               auto k = c->key();
///           }
///       }
///
///       void do_work() {
///           auto txn = kv::begin(0);        // returns own<transaction>
///           txn->insert(key, val);
///           // ~txn calls [resource-drop]transaction automatically
///       }
///
///    The proxy<import_dispatch<T>> generated by PSIO_REFLECT provides the
///    method stubs. Each stub serializes arguments via canonical ABI, calls
///    the corresponding WASM import, and deserializes the result. The guest
///    never sees raw u32 handles.
///
/// # Canonical ABI wire format
///
/// On the wire, both own<T> and borrow<T> are a single u32 — an index into the
/// component instance's handle table for type T.
///
///   - own<T>:    Transfers ownership. The receiving side gets a new handle
///                table entry. The sending side's entry is consumed.
///   - borrow<T>: Temporary reference. Valid only for the duration of the call.
///                The handle is not consumed and cannot be stored.
///
/// # Security model
///
/// A WASM guest can only access resources in its own per-component handle table.
/// A guest could fabricate u32 values to access any resource already in its table,
/// but cannot reach resources belonging to other component instances (separate
/// tables). Access control is enforced at resource creation time — if the host
/// policy says "component X may only access root 3", the host rejects the
/// factory call before a handle ever enters the table.
///
/// # WIT generation
///
/// The WIT generator (wit_gen.hpp) detects resources via is_wit_resource_v<T>,
/// which checks std::is_base_of<wit_resource, T>. For resource types:
///   - Data members are ignored (resources are opaque)
///   - Reflected methods become resource methods in the WIT output
///   - own<T> in return types emits `own<resource-name>`
///   - borrow<T> in parameters emits `borrow<resource-name>`
///
/// Generated WIT example:
///
///   resource cursor {
///       seek: func(key: list<u8>) -> bool;
///       next: func() -> bool;
///       key: func() -> list<u8>;
///       value: func() -> list<u8>;
///   }
///
///   open-cursor: func(root-index: u32) -> own<cursor>;

#include <cstdint>
#include <type_traits>
#include <utility>

namespace psio {

   // =========================================================================
   // wit_resource — empty base class marking a type as a WIT resource
   // =========================================================================

   /// Inherit from this to declare a type as a WIT resource.
   ///
   /// Resources are opaque handle types whose internal state does not cross
   /// the WASM boundary. Only their reflected methods are visible in WIT.
   /// Data members on resource types are ignored by the WIT generator.
   ///
   /// Example:
   ///    struct cursor : psio::wit_resource {
   ///        bool seek(std::vector<uint8_t> key);
   ///        bool next();
   ///    };
   ///    PSIO_REFLECT(cursor, method(seek, key), method(next))
   struct wit_resource {};

   // =========================================================================
   // is_wit_resource_v — trait detecting resource types
   // =========================================================================

   /// True if T inherits from wit_resource.
   ///
   /// The WIT generator uses this to decide whether a reflected type should
   /// be emitted as a `resource` (opaque, with methods) or a `record`
   /// (transparent, with data fields).
   template<typename T>
   constexpr bool is_wit_resource_v = std::is_base_of_v<wit_resource, T>;

   // =========================================================================
   // own<T> — owning handle to a resource
   // =========================================================================

   /// Represents ownership of a resource instance across the WASM boundary.
   ///
   /// Canonical ABI wire format: u32 (handle table index).
   ///
   /// Ownership semantics:
   ///   - Returning own<T> transfers the resource to the caller.
   ///     The caller receives a new handle table entry.
   ///   - Passing own<T> as a parameter transfers ownership to the callee.
   ///     The caller's handle is consumed and becomes invalid.
   ///   - Dropping own<T> calls [resource-drop] which destroys the resource.
   ///
   /// On the guest side, own<T> behaves like std::unique_ptr — it provides
   /// RAII cleanup and method access through operator->. The proxy generated
   /// by PSIO_REFLECT routes each method call through the WASM import
   /// dispatcher, prepending the handle as the first canonical ABI argument.
   ///
   /// On the host side, own<T> is a u32 index into the host's handle table
   /// for type T. The runtime resolves it to a concrete object pointer.
   ///
   /// Example in function signatures:
   ///    own<cursor> open_cursor(uint32_t root);  // factory: returns new handle
   ///    void close(own<cursor> c);               // consumer: takes ownership
   template<typename T> struct borrow;  // forward declaration

   template<typename T>
   struct own {
      static_assert(is_wit_resource_v<T>,
                    "own<T> requires T to inherit from psio::wit_resource");

      uint32_t handle;

      explicit own(uint32_t h) : handle(h) {}

      operator borrow<T>() const { return borrow<T>{handle}; }
   };

   // =========================================================================
   // borrow<T> — borrowed handle to a resource
   // =========================================================================

   /// Represents a temporary, non-owning reference to a resource instance.
   ///
   /// Canonical ABI wire format: u32 (handle table index).
   ///
   /// Borrow semantics:
   ///   - Valid only for the duration of the function call.
   ///   - The callee must not store the handle beyond the call's return.
   ///   - The resource is not destroyed when the borrow goes out of scope.
   ///   - Multiple borrows of the same resource can coexist.
   ///
   /// In WIT resource methods, the `self` parameter is implicitly a
   /// borrow<self>. The canonical ABI prepends a u32 handle as the first
   /// argument to each [method] import.
   ///
   /// Example in function signatures:
   ///    bool has_key(borrow<cursor> c, std::vector<uint8_t> key);
   template<typename T>
   struct borrow {
      static_assert(is_wit_resource_v<T>,
                    "borrow<T> requires T to inherit from psio::wit_resource");

      uint32_t handle;

      explicit borrow(uint32_t h) : handle(h) {}
   };

}  // namespace psio

// ── wasm_type_traits for own<T> and borrow<T> ──────────────────────
// Both map to u32 (handle table index) at the WASM ABI level.
namespace psizam {
   template<typename T, typename> struct wasm_type_traits;

   template<typename T>
   struct wasm_type_traits<psio::own<T>, void> {
      static constexpr bool is_wasm_type = true;
      using wasm_type = uint32_t;
      static constexpr uint32_t unwrap(psio::own<T> o) { return o.handle; }
      static constexpr psio::own<T> wrap(uint32_t v) { return psio::own<T>{v}; }
   };

   template<typename T>
   struct wasm_type_traits<psio::borrow<T>, void> {
      static constexpr bool is_wasm_type = true;
      using wasm_type = uint32_t;
      static constexpr uint32_t unwrap(psio::borrow<T> b) { return b.handle; }
      static constexpr psio::borrow<T> wrap(uint32_t v) { return psio::borrow<T>{v}; }
   };
} // namespace psizam
