//! Zero-copy pSSZ views. Format-parameterized counterpart of the C++
//! `pssz_view<T, F>` in `pssz_view.hpp`. Every accessor is pointer
//! arithmetic over the underlying buffer, no allocation, no
//! materialization.
//!
//! Differences from `ssz_view`:
//!   - Format parameter `F` picks offset/header widths (u8 / u16 / u32)
//!   - Reflected containers skip `F::HEADER_BYTES` before the fixed region
//!   - `Option<T>` with fixed `T` has no selector byte — presence derived
//!     from span (`None` ↔ 0 bytes, `Some` ↔ `sizeof(T)` bytes)
//!
//! The named-accessor methods on reflected structs are generated by the
//! `pssz_struct!` macro (parallel to how `ssz_struct!` generates named
//! accessors for `SszView`).

use crate::pssz::{Bitvector, Bitlist, BoundedList, BoundedString, PsszFormat, PsszPack, Uint256};

/// Zero-copy pSSZ view parameterized by target type `T` and format tag `F`.
#[derive(Debug, Clone, Copy)]
pub struct PsszView<'a, T: ?Sized, F: PsszFormat> {
    pub data: &'a [u8],
    _phantom: std::marker::PhantomData<(*const T, *const F)>,
}

impl<'a, T: ?Sized, F: PsszFormat> PsszView<'a, T, F> {
    pub fn new(data: &'a [u8]) -> Self {
        PsszView { data, _phantom: std::marker::PhantomData }
    }
    pub fn raw(&self) -> &'a [u8] { self.data }
}

// ── Primitives ──────────────────────────────────────────────────────────────

macro_rules! impl_pssz_view_primitive {
    ($($ty:ty),* $(,)?) => {$(
        impl<'a, F: PsszFormat> PsszView<'a, $ty, F> {
            pub fn get(&self) -> $ty {
                let mut buf = [0u8; std::mem::size_of::<$ty>()];
                buf.copy_from_slice(&self.data[..std::mem::size_of::<$ty>()]);
                <$ty>::from_le_bytes(buf)
            }
        }
    )*};
}
impl_pssz_view_primitive!(u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, f32, f64);

impl<'a, F: PsszFormat> PsszView<'a, bool, F> {
    pub fn get(&self) -> bool { self.data[0] != 0 }
}

impl<'a, F: PsszFormat> PsszView<'a, Uint256, F> {
    pub fn get(&self) -> Uint256 {
        let mut limb = [0u64; 4];
        for i in 0..4 {
            let mut b = [0u8; 8];
            b.copy_from_slice(&self.data[i * 8 .. (i + 1) * 8]);
            limb[i] = u64::from_le_bytes(b);
        }
        Uint256 { limb }
    }
}

// ── String / BoundedString ──────────────────────────────────────────────────

impl<'a, F: PsszFormat> PsszView<'a, String, F> {
    pub fn view(&self) -> &'a str {
        std::str::from_utf8(self.data).expect("pssz view: invalid UTF-8")
    }
    pub fn len(&self) -> usize { self.data.len() }
}

impl<'a, F: PsszFormat, const N: usize> PsszView<'a, BoundedString<N>, F> {
    pub fn view(&self) -> &'a str {
        std::str::from_utf8(self.data).expect("pssz view: invalid UTF-8")
    }
    pub fn len(&self) -> usize { self.data.len() }
}

// ── Vec / BoundedList ───────────────────────────────────────────────────────

impl<'a, T: PsszPack<F> + 'static, F: PsszFormat> PsszView<'a, Vec<T>, F> {
    pub fn len(&self) -> usize {
        if self.data.is_empty() { return 0; }
        if T::IS_FIXED_SIZE {
            self.data.len() / T::FIXED_SIZE
        } else {
            let ob = F::OFFSET_BYTES;
            let first = read_offset_u32::<F>(&self.data[..ob]);
            (first as usize) / ob
        }
    }
    pub fn is_empty(&self) -> bool { self.len() == 0 }
    pub fn get(&self, i: usize) -> PsszView<'a, T, F> {
        if T::IS_FIXED_SIZE {
            let elem = T::FIXED_SIZE;
            PsszView::new(&self.data[i * elem .. (i + 1) * elem])
        } else {
            let ob = F::OFFSET_BYTES;
            let n = self.len();
            let off_i = read_offset_u32::<F>(&self.data[i * ob .. (i + 1) * ob]) as usize;
            let off_next = if i + 1 < n {
                read_offset_u32::<F>(&self.data[(i + 1) * ob .. (i + 2) * ob]) as usize
            } else {
                self.data.len()
            };
            PsszView::new(&self.data[off_i .. off_next])
        }
    }
}

impl<'a, T: PsszPack<F> + 'static, F: PsszFormat, const N: usize>
    PsszView<'a, BoundedList<T, N>, F>
{
    pub fn len(&self) -> usize {
        // Same wire as Vec<T>, so construct a Vec view internally.
        let v: PsszView<'a, Vec<T>, F> = PsszView::new(self.data);
        v.len()
    }
    pub fn is_empty(&self) -> bool { self.len() == 0 }
    pub fn get(&self, i: usize) -> PsszView<'a, T, F> {
        let v: PsszView<'a, Vec<T>, F> = PsszView::new(self.data);
        v.get(i)
    }
}

// ── [T; N] ──────────────────────────────────────────────────────────────────

impl<'a, T: PsszPack<F> + 'static, F: PsszFormat, const N: usize>
    PsszView<'a, [T; N], F>
{
    pub const fn size() -> usize { N }
    pub fn get(&self, i: usize) -> PsszView<'a, T, F> {
        if T::IS_FIXED_SIZE {
            let elem = T::FIXED_SIZE;
            PsszView::new(&self.data[i * elem .. (i + 1) * elem])
        } else {
            let ob = F::OFFSET_BYTES;
            let off_i = read_offset_u32::<F>(&self.data[i * ob .. (i + 1) * ob]) as usize;
            let off_next = if i + 1 < N {
                read_offset_u32::<F>(&self.data[(i + 1) * ob .. (i + 2) * ob]) as usize
            } else {
                self.data.len()
            };
            PsszView::new(&self.data[off_i .. off_next])
        }
    }
}

// ── Option<T> — min-size-gated selector ────────────────────────────────────

impl<'a, T: PsszPack<F> + 'static, F: PsszFormat> PsszView<'a, Option<T>, F> {
    pub fn has_value(&self) -> bool {
        if T::MIN_ENCODED_SIZE == 0 {
            !self.data.is_empty() && self.data[0] == 1
        } else {
            !self.data.is_empty()
        }
    }
    pub fn unwrap(&self) -> PsszView<'a, T, F> {
        if T::MIN_ENCODED_SIZE == 0 {
            PsszView::new(&self.data[1..])
        } else {
            PsszView::new(self.data)
        }
    }
}

// ── Bit types ───────────────────────────────────────────────────────────────

impl<'a, F: PsszFormat, const N: usize> PsszView<'a, Bitvector<N>, F> {
    pub fn test(&self, i: usize) -> bool {
        (self.data[i >> 3] >> (i & 7)) & 1 != 0
    }
    pub const fn size(&self) -> usize { N }
}

impl<'a, F: PsszFormat, const MAX_N: usize> PsszView<'a, Bitlist<MAX_N>, F> {
    pub fn len(&self) -> usize {
        let mut last = self.data.len() as isize - 1;
        while last >= 0 && self.data[last as usize] == 0 { last -= 1; }
        if last < 0 { return 0; }
        let hi = 7 - self.data[last as usize].leading_zeros() as usize;
        (last as usize) * 8 + hi
    }
    pub fn test(&self, i: usize) -> bool {
        (self.data[i >> 3] >> (i & 7)) & 1 != 0
    }
}

// ── Offset width helpers ────────────────────────────────────────────────────

fn read_offset_u32<F: PsszFormat>(src: &[u8]) -> u32 {
    match F::OFFSET_BYTES {
        1 => src[0] as u32,
        2 => u16::from_le_bytes([src[0], src[1]]) as u32,
        4 => u32::from_le_bytes([src[0], src[1], src[2], src[3]]),
        _ => unreachable!(),
    }
}

/// Entry point matching C++ `psio::pssz_view_of<T, F>(buf)`.
pub fn pssz_view_of<'a, T: ?Sized, F: PsszFormat>(buf: &'a [u8]) -> PsszView<'a, T, F> {
    PsszView::new(buf)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pssz::{Pssz32, to_pssz};

    #[test]
    fn primitive_view() {
        let b = to_pssz::<Pssz32, _>(&0xDEADBEEFu32);
        let v: PsszView<u32, Pssz32> = pssz_view_of(&b);
        assert_eq!(v.get(), 0xDEADBEEF);
    }

    #[test]
    fn string_view() {
        let b = to_pssz::<Pssz32, _>(&"hello".to_string());
        let v: PsszView<String, Pssz32> = pssz_view_of(&b);
        assert_eq!(v.view(), "hello");
    }

    #[test]
    fn vec_fixed_view() {
        let v = vec![10u32, 20, 30];
        let b = to_pssz::<Pssz32, _>(&v);
        let view: PsszView<Vec<u32>, Pssz32> = pssz_view_of(&b);
        assert_eq!(view.len(), 3);
        assert_eq!(view.get(0).get(), 10);
        assert_eq!(view.get(2).get(), 30);
    }

    #[test]
    fn vec_variable_view() {
        let v: Vec<String> = vec!["a".into(), "bc".into(), "def".into()];
        let b = to_pssz::<Pssz32, _>(&v);
        let view: PsszView<Vec<String>, Pssz32> = pssz_view_of(&b);
        assert_eq!(view.len(), 3);
        assert_eq!(view.get(0).view(), "a");
        assert_eq!(view.get(2).view(), "def");
    }

    #[test]
    fn option_fixed_no_selector_view() {
        // Option<u32> has no selector in pSSZ.
        let some: Option<u32> = Some(42);
        let b = to_pssz::<Pssz32, _>(&some);
        let v: PsszView<Option<u32>, Pssz32> = pssz_view_of(&b);
        assert!(v.has_value());
        assert_eq!(v.unwrap().get(), 42);

        let none: Option<u32> = None;
        let b = to_pssz::<Pssz32, _>(&none);
        let v: PsszView<Option<u32>, Pssz32> = pssz_view_of(&b);
        assert!(!v.has_value());
    }

    #[test]
    fn option_variable_with_selector_view() {
        // Option<String> carries a selector.
        let some = Some("x".to_string());
        let b = to_pssz::<Pssz32, _>(&some);
        let v: PsszView<Option<String>, Pssz32> = pssz_view_of(&b);
        assert!(v.has_value());
        assert_eq!(v.unwrap().view(), "x");

        let none: Option<String> = None;
        let b = to_pssz::<Pssz32, _>(&none);
        let v: PsszView<Option<String>, Pssz32> = pssz_view_of(&b);
        assert!(!v.has_value());
    }
}
