#pragma once
#include <psizam/opcodes_def.hpp>
#include <psizam/variant.hpp>

#include <map>

namespace psizam {
   enum opcodes {
      PSIZAM_CONTROL_FLOW_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_BR_TABLE_OP(PSIZAM_CREATE_ENUM)
      PSIZAM_RETURN_OP(PSIZAM_CREATE_ENUM)
      PSIZAM_CALL_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_CALL_IMM_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_PARAMETRIC_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_VARIABLE_ACCESS_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_MEMORY_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_I32_CONSTANT_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_I64_CONSTANT_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_F32_CONSTANT_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_F64_CONSTANT_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_COMPARISON_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_NUMERIC_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_CONVERSION_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_EXIT_OP(PSIZAM_CREATE_ENUM)
      PSIZAM_REF_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_EXTENDED_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_EMPTY_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_ERROR_OPS(PSIZAM_CREATE_ENUM)
   };

   enum ext_opcodes {
       PSIZAM_DATA_OPS(PSIZAM_CREATE_ENUM)
       PSIZAM_EXT_OPS(PSIZAM_CREATE_ENUM)
   };

   enum vec_opcodes {
      PSIZAM_VEC_MEMORY_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_VEC_LANE_MEMORY_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_VEC_CONSTANT_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_VEC_SHUFFLE_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_VEC_LANE_OPS(PSIZAM_CREATE_ENUM)
      PSIZAM_VEC_NUMERIC_OPS(PSIZAM_CREATE_ENUM)
   };

   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         PSIZAM_CONTROL_FLOW_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_BR_TABLE_OP(PSIZAM_CREATE_MAP)
         PSIZAM_RETURN_OP(PSIZAM_CREATE_MAP)
         PSIZAM_CALL_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_CALL_IMM_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_PARAMETRIC_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_VARIABLE_ACCESS_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_MEMORY_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_I32_CONSTANT_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_I64_CONSTANT_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_F32_CONSTANT_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_F64_CONSTANT_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_COMPARISON_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_NUMERIC_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_CONVERSION_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_EXIT_OP(PSIZAM_CREATE_MAP)
         PSIZAM_REF_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_EXTENDED_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_EMPTY_OPS(PSIZAM_CREATE_MAP)
         PSIZAM_ERROR_OPS(PSIZAM_CREATE_MAP)
      };
   };

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   PSIZAM_CONTROL_FLOW_OPS(PSIZAM_CREATE_CONTROL_FLOW_TYPES)
   PSIZAM_BR_TABLE_OP(PSIZAM_CREATE_BR_TABLE_TYPE)
   PSIZAM_RETURN_OP(PSIZAM_CREATE_CONTROL_FLOW_TYPES)
   PSIZAM_CALL_OPS(PSIZAM_CREATE_CALL_TYPES)
   PSIZAM_CALL_IMM_OPS(PSIZAM_CREATE_CALL_IMM_TYPES)
   PSIZAM_PARAMETRIC_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_VARIABLE_ACCESS_OPS(PSIZAM_CREATE_VARIABLE_ACCESS_TYPES)
   PSIZAM_MEMORY_OPS(PSIZAM_CREATE_MEMORY_TYPES)
   PSIZAM_I32_CONSTANT_OPS(PSIZAM_CREATE_I32_CONSTANT_TYPE)
   PSIZAM_I64_CONSTANT_OPS(PSIZAM_CREATE_I64_CONSTANT_TYPE)
   PSIZAM_F32_CONSTANT_OPS(PSIZAM_CREATE_F32_CONSTANT_TYPE)
   PSIZAM_F64_CONSTANT_OPS(PSIZAM_CREATE_F64_CONSTANT_TYPE)
   PSIZAM_COMPARISON_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_NUMERIC_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_CONVERSION_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_EXIT_OP(PSIZAM_CREATE_EXIT_TYPE)

   // Reference type opcodes — manually defined since they have different layouts
   struct ref_null_t { uint8_t type; static constexpr uint8_t opcode = 0xD0; };
   struct ref_is_null_t { static constexpr uint8_t opcode = 0xD1; };
   struct ref_func_t { uint32_t index; static constexpr uint8_t opcode = 0xD2; };

   PSIZAM_EMPTY_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_ERROR_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_DATA_OPS(PSIZAM_CREATE_DATA_TYPES)
   PSIZAM_EXT_OPS(PSIZAM_CREATE_TYPES)
   PSIZAM_VEC_MEMORY_OPS(PSIZAM_CREATE_VEC_MEMORY_TYPES)
   PSIZAM_VEC_LANE_MEMORY_OPS(PSIZAM_CREATE_VEC_LANE_MEMORY_TYPES)
   PSIZAM_VEC_CONSTANT_OPS(PSIZAM_CREATE_V128_CONSTANT_TYPE)
   PSIZAM_VEC_SHUFFLE_OPS(PSIZAM_CREATE_VEC_SHUFFLE_TYPE)
   PSIZAM_VEC_LANE_OPS(PSIZAM_CREATE_VEC_LANE_TYPES)
   PSIZAM_VEC_NUMERIC_OPS(PSIZAM_CREATE_VEC_TYPES)

   using opcode = variant<
      PSIZAM_CONTROL_FLOW_OPS(PSIZAM_IDENTITY)
      PSIZAM_BR_TABLE_OP(PSIZAM_IDENTITY)
      PSIZAM_RETURN_OP(PSIZAM_IDENTITY)
      PSIZAM_CALL_OPS(PSIZAM_IDENTITY)
      PSIZAM_CALL_IMM_OPS(PSIZAM_IDENTITY)
      PSIZAM_PARAMETRIC_OPS(PSIZAM_IDENTITY)
      PSIZAM_VARIABLE_ACCESS_OPS(PSIZAM_IDENTITY)
      PSIZAM_MEMORY_OPS(PSIZAM_IDENTITY)
      PSIZAM_I32_CONSTANT_OPS(PSIZAM_IDENTITY)
      PSIZAM_I64_CONSTANT_OPS(PSIZAM_IDENTITY)
      PSIZAM_F32_CONSTANT_OPS(PSIZAM_IDENTITY)
      PSIZAM_F64_CONSTANT_OPS(PSIZAM_IDENTITY)
      PSIZAM_COMPARISON_OPS(PSIZAM_IDENTITY)
      PSIZAM_NUMERIC_OPS(PSIZAM_IDENTITY)
      PSIZAM_CONVERSION_OPS(PSIZAM_IDENTITY)
      PSIZAM_EXIT_OP(PSIZAM_IDENTITY)
      ref_null_t, ref_is_null_t, ref_func_t,
      PSIZAM_EMPTY_OPS(PSIZAM_IDENTITY)
      PSIZAM_DATA_OPS(PSIZAM_IDENTITY)
      PSIZAM_EXT_OPS(PSIZAM_IDENTITY)
      PSIZAM_VEC_MEMORY_OPS(PSIZAM_IDENTITY)
      PSIZAM_VEC_LANE_MEMORY_OPS(PSIZAM_IDENTITY)
      PSIZAM_VEC_CONSTANT_OPS(PSIZAM_IDENTITY)
      PSIZAM_VEC_SHUFFLE_OPS(PSIZAM_IDENTITY)
      PSIZAM_VEC_LANE_OPS(PSIZAM_IDENTITY)
      PSIZAM_VEC_NUMERIC_OPS(PSIZAM_IDENTITY)
      PSIZAM_ERROR_OPS(PSIZAM_IDENTITY_END)
      >;
} // namespace psizam
